sudo() messages to pass data from Go code to CosmWasm #LSC-31
neutron-org/neutron pull request #10
Opened 2022-06-09 08:12 UTC by ratik

https://p2pvalidator.atlassian.net/browse/LSC-31

Make sure you are testing this one with proper branch of contracts (feat/sudo)

https://github.com/lidofinance/lido-interchain-staking-contracts/pull/26

Please note that as for now ibc returns only one error for interchain tx errors: `ABCI code: 5: error handling packet on host chain: see events for details` so we may want to retrieve actual error from events bc acknowledge data just don't have any in it itself

2022-06-16 09:00 UTC, foxpy requested changes

2022-06-16 09:00 UTC, foxpy commented on register-interchain-account.sh
> +gaia-wasm-zoned tx interchaintxs register-interchain-account connection-0 cosmos1mjk79fjjgpplak5wq838w0yd982gzkyfrk07am \
I would move `cosmos1mjk79fjjgpplak5wq838w0yd982gzkyfrk07am` into a named constant to provide better understanding on purpose of this account

2022-06-16 09:00 UTC, foxpy commented on x/interchaintxs/client/cli/tx.go
> +					panic(err)
Is it really okay to panic here (I doubt)?
If it is okay to panic, then feel free to resolve this thread.
If it is not okay, please leave a TODO comment to deal with it later.

2022-06-16 09:00 UTC, foxpy commented on x/interchaintxs/client/cli/tx.go
> +						panic(err)
and same here

2022-06-16 18:30 UTC, mmikev commented on register-interchain-account.sh
> +export OWNER=$(gaia-wasm-zoned keys list  --keyring-backend test --home ./data/test-1 --output json | jq -r -c '.[] | select(.name == "rly1") | .address') && echo $OWNER;
Why not just `gaia-wasm-zoned keys show rly1 -a --keyring-backend test --home ./data/test-1`?

2022-06-16 18:30 UTC, mmikev commented on send_test_tx.sh
> +export OWNER=$(gaia-wasm-zoned keys list  --keyring-backend test --home ./data/test-1 --output json | jq -r -c '.[] | select(.name == "rly1") | .address') && echo $OWNER;
`gaia-wasm-zoned keys show rly1 -a --keyring-backend test --home ./data/test-1`?

2022-06-17 13:41 UTC, NeverHappened commented on x/interchaintxs/keeper/ibc_handlers.go
> +	m, err := json.Marshal(SudoMessage{
Not sure if it belongs here, but question to everybody:
How can we then find in smartcontracts what zone did we get response for?
I believe that matching by connection_id is not the easy way)

2022-06-19 09:07 UTC, zavgorodnii commented on x/interchaintxs/keeper/ibc_handlers.go
> +	m, err := json.Marshal(SudoMessage{
That's a good question (not just the connection id, connection id + port id, i guess?..). 

But:

1. Is it really that hard?
2. What's a better way to do it? Put the zone id to tx memo?

2022-06-19 16:30 UTC, foxpy approved these changes

2022-06-22 08:10 UTC, pr0n00gler approved these changes
Would be nice to have couple words in readme about how to test/see in work this PR (if it works of course)

2022-06-22 18:07 UTC, sotnikov-s requested changes

2022-06-22 18:07 UTC, sotnikov-s commented on x/interchaintxs/client/cli/tx.go
> -				if err := cdc.UnmarshalInterfaceJSON(contents, &txMsgs); err != nil {
I know it's out of scope, but could you please fix the short description of this cobra command above?

2022-06-22 18:07 UTC, sotnikov-s commented on x/interchaintxs/keeper/ibc_handlers.go
> +)
please add a `SudoMsgType...` prefix to the constants. otherwise, for example, a standalone `Error` looks strange in the code. it's a good widespread practice — to prefix enums-like constants with the type they represent.
```golang
_, err = k.Sudo(ctx, Error, hubContractAddress, packet, []byte{}, []byte(errorText))
```

2022-06-22 18:07 UTC, sotnikov-s commented on x/interchaintxs/types/tx.go
> +func (msg MsgSubmitTx) UnpackInterfaces(unpacker codectypes.AnyUnpacker) error {
unused func?

2022-06-22 18:07 UTC, sotnikov-s commented on x/interchaintxs/keeper/ibc_handlers.go
> +	error []byte,
please rename the parameter to err because it looks confusing in the code editor. it's a common practice to shorten error variables to err
<img width="287" alt="image" src="https://user-images.githubusercontent.com/34917380/175104238-7fbd5627-6b6f-4305-b982-dc2041600143.png">

2022-06-22 18:07 UTC, sotnikov-s commented on x/interchaintxs/keeper/ibc_handlers.go
> +	if err := channeltypes.SubModuleCdc.UnmarshalJSON(acknowledgement, &ack); err != nil {
the SubModuleCdc description claims:
SubModuleCdc references the global x/ibc/core/04-channel module codec. Note, **the codec should ONLY be used in certain instances of tests** and for JSON encoding.

can we use it actually? is there a production ready alternative?

2022-06-22 18:07 UTC, sotnikov-s commented on x/interchaintxs/keeper/ibc_handlers.go
> +		return sdkerrors.Wrapf(sdkerrors.ErrUnknownRequest, "cannot unmarshal ICS-27 packet acknowledgement: %v", err)
please use %w for returned errors

2022-06-22 18:07 UTC, sotnikov-s commented on x/interchaintxs/keeper/ibc_handlers.go
> +	_, err = k.Sudo(ctx, OpenAck, hubContractAddress, channeltypes.Packet{}, []byte(portID+channelID+counterPartyChannelId+counterpartyVersion), []byte{})
I don't really like the way the Sudo func is designed: not all parameters are used which results in empty arguments passed. what do you think about replacing the keeper's Sudo method with four methods — one on each SudoMessageType and with only the required parameters? e.g. execSudoOpenAck, execSudoError etc. it will also become possible to make logging more precise and concise in these methods

2022-06-22 18:07 UTC, sotnikov-s commented on x/interchaintxs/keeper/ibc_handlers.go
> +type SudoMessageType uint
how do you find making the SudoMessageType of type string with more detailed values? it will make it possible to use this type in logging which will result in a better UX for us

2022-06-22 18:10 UTC, sotnikov-s reviewed
_ignore_

2022-06-22 18:12 UTC, sotnikov-s commented on test_tx.json
> +}
if I understand it correctly, the .sh files you've introduced and this json are made for tests. I think it would be more clean to move them to a dedicated folder and maybe even add a makefile in the root of the project that executes the .sh files in the order you need. what do you think?

2022-06-22 21:24 UTC, mmikev commented on x/interchaintxs/types/tx.go
> +func (msg MsgSubmitTx) UnpackInterfaces(unpacker codectypes.AnyUnpacker) error {
It's actually implements [`UnpackInterfacesMessage.UnpackInterfaces`](https://github.com/cosmos/cosmos-sdk/blob/d07d35f29e0a0824b489c552753e8798710ff5a8/codec/types/interface_registry.go#L60).

Would be good to add a comment about this, I agree.

And add 
```go
var (
	_ codectypes.UnpackInterfacesMessage = MsgSubmitTx{}
)

```

at the top of the file to check that the message satisfies the interface

2022-06-23 05:23 UTC, sotnikov-s commented on x/interchaintxs/types/tx.go
> +func (msg MsgSubmitTx) UnpackInterfaces(unpacker codectypes.AnyUnpacker) error {
... and add a comment describing this idea to the empty interface check variable (they are sometimes confusing)

2022-06-23 06:02 UTC, ratik commented on x/interchaintxs/keeper/ibc_handlers.go
> +	error []byte,
not sure we really need to do it bc we already have `err` var in fn scope which is returned. so me personally prefer to keep err var name for returned var

2022-06-23 06:04 UTC, ratik commented on x/interchaintxs/keeper/ibc_handlers.go
> +	if err := channeltypes.SubModuleCdc.UnmarshalJSON(acknowledgement, &ack); err != nil {
this peace of code been borrowed from interchain-demo, also I checked other ways and hadn't found any alternatives

2022-06-23 06:11 UTC, ratik commented on x/interchaintxs/keeper/ibc_handlers.go
> +	_, err = k.Sudo(ctx, OpenAck, hubContractAddress, channeltypes.Packet{}, []byte(portID+channelID+counterPartyChannelId+counterpartyVersion), []byte{})
can't agree, this way we gonna have several copypasted functions which do almost the same stuff

2022-06-23 06:42 UTC, ratik commented on x/interchaintxs/types/tx.go
> +func (msg MsgSubmitTx) UnpackInterfaces(unpacker codectypes.AnyUnpacker) error {
fixed

2022-06-23 07:01 UTC, ratik commented
> Would be nice to have couple words in readme about how to test/see in work this PR (if it works of course)

sure will do, when we have it ready on contract side. As for now you have it's kinda complex to actually test

2022-06-23 07:02 UTC, ratik commented on test_tx.json
> +}
sure, I think it would be nice to have separate task for it bc there are other test-related stuff to move

2022-06-23 07:09 UTC, mmikev commented on x/interchaintxs/keeper/ibc_handlers.go
> +		return sdkerrors.Wrapf(sdkerrors.ErrUnknownRequest, "cannot unmarshal ICS-27 packet acknowledgement: %v", err)
Actually, `sdkerrors.Wrapf()` does not support `%w`

2022-06-23 09:26 UTC, ratik commented on x/interchaintxs/keeper/ibc_handlers.go
> +		return sdkerrors.Wrapf(sdkerrors.ErrUnknownRequest, "cannot unmarshal ICS-27 packet acknowledgement: %v", err)
oh nice

2022-06-23 09:28 UTC, ratik commented on x/interchaintxs/keeper/ibc_handlers.go
> +	m, err := json.Marshal(SudoMessage{
so we had a conversation with @swelf19 and @NeverHappened and figured out that this info stored in hub storage so we could find proper zone on contract side

2022-06-23 09:30 UTC, sotnikov-s commented on x/interchaintxs/keeper/ibc_handlers.go
> +		return sdkerrors.Wrapf(sdkerrors.ErrUnknownRequest, "cannot unmarshal ICS-27 packet acknowledgement: %v", err)
yeah, my bad!

2022-06-23 15:01 UTC, sotnikov-s commented on x/interchaintxs/keeper/ibc_handlers.go
> +	error []byte,
okay, errorMsg then?
and also: the parameter type is []byte whereas you
1) pass string arguments to this func calls;
2) cast parameters back to string.
so I'd make the parameters string and rename error to errorMsg

2022-06-23 15:01 UTC, sotnikov-s commented on x/interchaintxs/keeper/ibc_handlers.go
> +	_, err = k.Sudo(ctx, OpenAck, hubContractAddress, channeltypes.Packet{}, []byte(portID+channelID+counterPartyChannelId+counterpartyVersion), []byte{})
matter of taste :) but okay, I don't insist ofc

2022-06-23 15:04 UTC, sotnikov-s commented on x/interchaintxs/keeper/ibc_handlers.go
> +type SudoMessageType uint
moreover, matching on the uint type on the smart contracts side that possibly may be messed in the future is definitely worth switching to string type imo

2022-06-24 16:07 UTC, foxpy approved these changes

2022-06-28 09:20 UTC, sotnikov-s approved these changes
a little misprint. the rest LGTM

2022-06-28 09:20 UTC, sotnikov-s commented on x/interchaintxs/keeper/ibc_handlers.go
> +	CounterPartyChannelId string `json:"counter_party_channel_id"`
CounterPartyChannelId -> CounterpartyChannelId
counter_party_channel_id -> counterparty_channel_id
right?

2022-06-28 11:50 UTC, mmikev commented on demo/init_contracts.sh
> +sleep 5;
I think we can avoid `sleep` calls if commands to send transactions contain `broadcast-mode block` flag?

2022-06-28 11:53 UTC, mmikev commented on demo/init_contracts.sh
> +sleep 5;
And `gaia-wasm-zoned` has `--output json` flag to print output in json, so you can use `jq` instead of greps, which can be more convenient

2022-06-28 11:54 UTC, mmikev commented on demo/init_contracts.sh
> +sleep 5;
Ah, I see you use that in other commands

2022-06-28 11:56 UTC, pr0n00gler approved these changes

2022-06-28 13:01 UTC, zavgorodnii approved these changes

2022-06-28 13:52 UTC, NeverHappened approved these changes

2022-06-28 15:09 UTC, foxpy approved these changes

2022-06-28 15:21 UTC, merged