Feat/tx memo
neutron-org/neutron pull request #11
Opened 2022-06-15 15:17 UTC by NeverHappened

https://p2pvalidator.atlassian.net/browse/LSC-39

See the https://github.com/lidofinance/lido-interchain-staking-contracts/pull/29 for contracts side of memo addition.

Added memo to SubmitTx message and to acknowledgement packet. I've tested it and it returns the memo back.

Test steps:
Use the ./gaia-wasm-zone/demo/readme.md to run test steps, but also need to add logging on acknowledgement to see memo returned back

2022-06-19 16:35 UTC, foxpy requested changes

2022-06-19 16:35 UTC, foxpy commented on proto/interchaintxs/v1/tx.proto
> +  repeated google.protobuf.Any msgs = 5;
Please don't reorder protobuf message fields, they are sequentially enumerated for a good reason.

This is probably not going to cause any issues for our project (though I cannot prove it), but still.

Better safe than sorry.

2022-06-20 08:15 UTC, NeverHappened commented on proto/interchaintxs/v1/tx.proto
> +  repeated google.protobuf.Any msgs = 5;
Good point, actually It didn't work that way, and I redid it

2022-06-29 13:12 UTC, zavgorodnii commented
only one consideration — maybe we shouldn't make the memo a required command line argument?.. i mean, not everyone needs a memo

2022-06-30 08:27 UTC, zavgorodnii commented on x/interchaintxs/client/cli/tx.go
> +			memo := args[3]
I don't get it. You set MinimumNArgs(3), and here you always take the 4-th element of an array that might not have 4 elements.

2022-06-30 08:33 UTC, ratik commented on x/interchaintxs/client/cli/tx.go
> +			memo := args[3]
btw, should we check memo length here or somewhere else?

2022-06-30 10:38 UTC, NeverHappened commented on x/interchaintxs/client/cli/tx.go
> +			memo := args[3]
probably should in the message server handler. I also want to find where the real limit on memo is set in code

2022-06-30 10:46 UTC, ratik commented on x/interchaintxs/client/cli/tx.go
> +			memo := args[3]
https://github.com/cosmos/cosmos-sdk/blob/6f070623741fe0d6851d79ada41e6e2b1c67e236/x/auth/types/params.go#L13

2022-07-01 09:50 UTC, zavgorodnii approved these changes

2022-07-01 10:01 UTC, pr0n00gler approved these changes

2022-07-01 10:07 UTC, ratik approved these changes

2022-07-01 10:10 UTC, foxpy requested changes

2022-07-01 10:10 UTC, foxpy commented on x/interchaintxs/client/cli/tx.go
> +		Use:     "submit-tx [connection-id] [owner] [path/to/sdk_msgs.json] [memo]",
Hmmm, this help message implies (people usually use square brackets to mark optional arguments) that connection-id, owner, path and memo are all optional arguments, but they are not. I am providing my own suggestion but I am not really sure about it neither.

```suggestion
		Use:     "submit-tx connection-id owner path/to/sdk_msgs.json [memo]",
```

2022-07-01 10:26 UTC, mmikev commented on x/interchaintxs/client/cli/tx.go
> +		Use:     "submit-tx [connection-id] [owner] [path/to/sdk_msgs.json] [memo]",
It's a common practice in Cosmos-SDK to wrap arguments in square brackets. So I'd stick with current version

2022-07-01 10:29 UTC, mmikev commented on x/interchaintxs/client/cli/tx.go
> +		Use:     "submit-tx [connection-id] [owner] [path/to/sdk_msgs.json] [memo]",
But I'd personally pass memo via flag, not argument. This shows that memo is optional

2022-07-01 11:05 UTC, foxpy commented on x/interchaintxs/client/cli/tx.go
> +		Use:     "submit-tx [connection-id] [owner] [path/to/sdk_msgs.json] [memo]",
Well, if it is a common practice, then I am leaving an approving review. And at the same time anyone is free to change arguments hint if desirable.

2022-07-01 11:06 UTC, foxpy approved these changes

2022-07-01 12:43 UTC, NeverHappened commented on x/interchaintxs/client/cli/tx.go
> +		Use:     "submit-tx [connection-id] [owner] [path/to/sdk_msgs.json] [memo]",
Changed to flag, did I do it ok?)

2022-07-01 12:49 UTC, swelf19 approved these changes

2022-07-01 13:02 UTC, zavgorodnii approved these changes
i have no time to test it like i did the last time, but i really hope that this works.

2022-07-02 04:30 UTC, foxpy commented on x/interchaintxs/client/cli/tx.go
> +		Use:     "submit-tx [connection-id] [owner] [path/to/sdk_msgs.json] [memo]",
looks alright, though @pr0n00gler told us that:
> It's a common practice in Cosmos-SDK to wrap arguments in square brackets
so I am not 100% sure.

@pr0n00gler what do you think about it?

2022-07-02 13:22 UTC, mmikev commented on x/interchaintxs/client/cli/tx.go
> +		Use:     "submit-tx [connection-id] [owner] [path/to/sdk_msgs.json] [memo]",
I think we should return square brackets here for consistency

2022-07-04 08:42 UTC, sotnikov-s requested changes

2022-07-04 08:42 UTC, sotnikov-s commented on x/interchaintxs/client/cli/tx.go
> +		Use:     "submit-tx [connection-id] [owner] [path/to/sdk_msgs.json] --memo memo",
this seems to be redundant cause you add the flag at the line 143

2022-07-04 08:42 UTC, sotnikov-s commented on x/interchaintxs/client/cli/tx.go
> +const Memo = "memo"
please add a Flag suffix to the constant name cuz otherwise it's misleading what is the `Memo` in the code

2022-07-06 13:27 UTC, sotnikov-s approved these changes

2022-07-06 13:28 UTC, merged