Feat: submit transactions improvements
neutron-org/neutron pull request #12
Opened 2022-06-21 13:12 UTC by pr0n00gler

**MERGE ONLY WITH** https://github.com/lidofinance/cosmos-query-relayer/pull/6

This PR solves:
* https://p2pvalidator.atlassian.net/jira/software/projects/LSC/boards/121?selectedIssue=LSC-37
* https://p2pvalidator.atlassian.net/jira/software/projects/LSC/boards/121?selectedIssue=LSC-46
* and some problems that are not described in JIRA.

What's changed:
* transaction results are saved in new way now to easily iterate on them and support limit/offset features;
* `QueryTransactions` query method is implemented for convenient querying transactions results with limit/offset;
* `MsgSubmitQueryResult` is changed for more convenient usage;
* `MsgSubmitQueryResult` contains `BlockHeader` and `NextBlockHeader` to verify transactions;
* interchain queries module performs verification of the headers and transactions now;
* `RevisionNumber` is not hardcoded anymore;
* `readme.md` is updated a little;
* tests are implemented for verification and msg_server logic in interchain queries module.

2022-06-23 12:02 UTC, foxpy requested changes

2022-06-23 12:02 UTC, foxpy commented on readme.md
> +* Result for transactions search query (in our case MsgBankSend and this query id is 2, and we set limit and offser to 1 and 100 respectively):
offse**r**

2022-06-23 12:02 UTC, foxpy commented on x/interchainqueries/keeper/abci.go
> +				k.Logger(ctx).Error("failed to save query: %v", err)
shouldn't it be possible to use %w here?

2022-06-23 12:08 UTC, foxpy commented on x/interchainqueries/keeper/keeper_test.go
> +		malleate    func()
what is `malleate`?

2022-06-23 12:12 UTC, foxpy commented on x/interchainqueries/keeper/keeper_test.go
> +			suite.Require().NoError(err)
Looks like a double error check

2022-06-23 12:12 UTC, mmikev commented on x/interchainqueries/keeper/keeper_test.go
> +		malleate    func()
It's a common name in cosmos-sdk tests for function that "prepares" (malleate) some data for testing. Since I copypasted a testing template from sdk, so this name moved to us too

2022-06-23 12:16 UTC, foxpy commented on x/interchainqueries/keeper/keeper_test.go
> +		malleate    func()
Didn't know it is an actual verb in English!

2022-06-23 12:19 UTC, mmikev commented on x/interchainqueries/keeper/keeper_test.go
> +			suite.Require().NoError(err)
Why?

If we expect error -> we check that returned error is the same as we expect and response is nil.
If we don't expect error -> we check that error is nil and response is not nil

2022-06-23 16:18 UTC, mmikev commented on readme.md
> +* Result for transactions search query (in our case MsgBankSend and this query id is 2, and we set limit and offser to 1 and 100 respectively):
Fixed

2022-06-23 16:18 UTC, mmikev commented on x/interchainqueries/keeper/abci.go
> +				k.Logger(ctx).Error("failed to save query: %v", err)
Fixed

2022-06-24 15:31 UTC, foxpy commented on x/interchainqueries/keeper/keeper_test.go
> +			suite.Require().NoError(err)
yep, I am wrong

2022-06-24 16:01 UTC, foxpy requested changes

2022-06-24 16:01 UTC, foxpy commented on x/interchainqueries/types/tx.go
> +	if msg.Result.KvResults == nil && msg.Result.Blocks == nil {
I think it might be a good idea to actually check that we have some values in these arrays:
```suggestion
	if len(msg.Result.KvResults) == 0 && len(msg.Result.Blocks) == 0 {
```

2022-06-27 14:25 UTC, foxpy approved these changes

2022-06-29 12:39 UTC, zavgorodnii commented on x/interchainqueries/keeper/keeper.go
> +	}
shouldn't we exit here? can we have both blocks and kvresults?

2022-06-29 12:50 UTC, zavgorodnii commented on x/interchainqueries/keeper/verify.go
> +	// check that inclusion proof and delivery proof are for the same transaction
<3

2022-06-29 12:55 UTC, zavgorodnii commented on x/interchaintxs/keeper/keeper.go
> +	return sdk.AccAddress("hub_address"), nil // Just for now while setting the hub address is not available
i think that after merging the sudo PR this is not what we want to have, right?

2022-06-29 12:55 UTC, zavgorodnii commented on x/interchaintxs/keeper/keeper.go
> +	return sdk.AccAddress("hub_address"), nil // Just for now while setting the hub address is not available
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/6124982/176441403-0eb15cad-c251-470d-9d32-e5750a0f66b3.png">

2022-06-30 09:16 UTC, mmikev commented on x/interchainqueries/keeper/keeper.go
> +	}
Theoretically yes, but the relayer does not support this feature now (it sends blocks and kvresults in separate messages)

2022-06-30 09:16 UTC, mmikev commented on x/interchaintxs/keeper/keeper.go
> +	return sdk.AccAddress("hub_address"), nil // Just for now while setting the hub address is not available
After merging with master, we have the code from the sudo PR here

2022-06-30 11:03 UTC, zavgorodnii approved these changes

2022-06-30 11:57 UTC, ratik approved these changes

2022-07-01 08:25 UTC, zavgorodnii approved these changes

2022-07-01 08:47 UTC, merged