rm intechainadapter mentions NTRN-299
neutron-org/neutron pull request #126
Opened 2023-01-13 11:40 UTC by quasisamurai

2023-01-13 14:12 UTC, foxpy requested changes
Running `grep --exclude-dir=.git -R interchainadapter .` I can still see mentions of interchainadapter.

2023-01-16 11:53 UTC, pr0n00gler submitted a review, later dismissed

2023-01-19 10:55 UTC, sotnikov-s commented on docs/static/openapi.yml
> +      operationId: NeutronInterchainqueriesQueryResult
here and below: NeutronInterchain**q**ueries -> NeutronInterchain**Q**ueries

2023-01-19 10:55 UTC, sotnikov-s commented on proto/interchainqueries/genesis.proto
> +// GenesisState defines the neutron module's genesis state.
defines the **neutron** module's -> defines the **interchainqueries** module's

2023-01-19 10:55 UTC, sotnikov-s commented on proto/interchaintxs/v1/genesis.proto
> +// GenesisState defines the neutron module's genesis state.
defines the **neutron** module's -> defines the **interchaintxs** module's

2023-01-19 13:31 UTC, foxpy requested changes
I can still see mentions of interchain adapter: `grep --exclude-dir=data --exclude-dir=.git -i -I -R adapter .`

2023-01-20 11:35 UTC, foxpy approved these changes

2023-01-20 12:14 UTC, sotnikov-s approved these changes

2023-01-20 12:54 UTC, merged