chore: rebranding
neutron-org/neutron pull request #15
Opened 2022-07-05 14:07 UTC by swelf19

rebranding. Ranemed org, renamed app
lidofinance -> neutron-org
gaia-wasm-zone -> neutron

2022-07-06 09:06 UTC, pr0n00gler approved these changes

2022-07-06 09:13 UTC, mmikev commented on app/app.go
>  	AccountAddressPrefix = "cosmos"
neutron?

2022-07-07 07:28 UTC, quasisamurai approved these changes

2022-07-07 07:29 UTC, ratik commented on app/app.go
> +	Name                 = "neutrond"
so `AccountAddressPrefix` is not needed anymore?

2022-07-07 08:30 UTC, swelf19 commented on app/app.go
> +	Name                 = "neutrond"
Actually the cons was not used anywhere in the code. Now we configure prefixes at this place https://github.com/neutron-org/neutron/blob/chore/rebranding/cmd/neutrond/main.go#L12.

2022-07-07 08:35 UTC, NeverHappened approved these changes

2022-07-07 08:36 UTC, ratik approved these changes

2022-07-07 13:02 UTC, sotnikov-s requested changes
cmd+shift+F on `lido` still results in several matches particularly in the `./demo/` folder

2022-07-07 13:02 UTC, sotnikov-s commented on x/interchaintxs/types/tx.pb.go
> +	err := c.cc.Invoke(ctx, "/neutron_org.interchainadapter.interchaintxs.v1.Msg/RegisterInterchainAccount", in, out, opts...)
don't really like this neutron **_org** suffix. let's simply use neutron?

2022-07-07 13:07 UTC, swelf19 commented
> cmd+shift+F on `lido` still results in several matches particularly in the `./demo/` folder

as far as i can see its only lido's contracts

2022-07-07 13:10 UTC, swelf19 commented on x/interchaintxs/types/tx.pb.go
> +	err := c.cc.Invoke(ctx, "/neutron_org.interchainadapter.interchaintxs.v1.Msg/RegisterInterchainAccount", in, out, opts...)
my first thought was the same, but second thought - lidofinance its an org, so lets replace with another org. we can vote with emojis i think

2022-07-07 13:41 UTC, sotnikov-s commented
> > cmd+shift+F on `lido` still results in several matches particularly in the `./demo/` folder
> 
> as far as i can see its only lido's contracts

do we need them in the repo? maybe we should move the helpers to the interchain staking repo? this is doubtfully the place for lido contracts: as far as I understand, it's going to become a public neutron daemon repository

2022-07-07 13:46 UTC, sotnikov-s commented on x/interchaintxs/types/tx.pb.go
> +	err := c.cc.Invoke(ctx, "/neutron_org.interchainadapter.interchaintxs.v1.Msg/RegisterInterchainAccount", in, out, opts...)
didn't get the thing about lidofinance is org, wym? we didn't have the _org suffix when the paths had lidofinance prefix

2022-07-08 07:14 UTC, foxpy requested changes
It doesn't look right at all.

![image](https://user-images.githubusercontent.com/24505352/177937776-ffa7653e-6a5b-4150-a16b-828b43d654dd.png)

2022-07-08 10:30 UTC, NeverHappened requested changes
Don't know if this is only my problem, but make `build && make init` fails:
```
Starting test-1 in ./data...
Creating log file at ./data/test-1.log
Starting test-2 in ./data...
Creating log file at ./data/test-2.log
Initializing relayer...
./network/hermes/restore-keys.sh
Success: Restored key 'testkey' (neutron1mjk79fjjgpplak5wq838w0yd982gzkyf8fxu8u) on chain test-1
Success: Restored key 'testkey' (neutron17dtl0mjt3t77kpuhg2edqzjpszulwhgzcdvagh) on chain test-2
./network/hermes/create-conn.sh
Initiating connection handshake...
Error: relayer error: RPC error to endpoint http://127.0.0.1:16657/: response error: Internal error: open data/test-1/data/blockstore.db/000034.sst: no such file or directory (code: -32603)
make: *** [init] Error 1
```

2022-07-08 13:26 UTC, swelf19 commented
> Don't know if this is only my problem, but make `build && make init` fails:
> 
> ```
> Starting test-1 in ./data...
> Creating log file at ./data/test-1.log
> Starting test-2 in ./data...
> Creating log file at ./data/test-2.log
> Initializing relayer...
> ./network/hermes/restore-keys.sh
> Success: Restored key 'testkey' (neutron1mjk79fjjgpplak5wq838w0yd982gzkyf8fxu8u) on chain test-1
> Success: Restored key 'testkey' (neutron17dtl0mjt3t77kpuhg2edqzjpszulwhgzcdvagh) on chain test-2
> ./network/hermes/create-conn.sh
> Initiating connection handshake...
> Error: relayer error: RPC error to endpoint http://127.0.0.1:16657/: response error: Internal error: open data/test-1/data/blockstore.db/000034.sst: no such file or directory (code: -32603)
> make: *** [init] Error 1
> ```

are there any errors above the screen? Does the error still happen? I cant reproduce it

2022-07-08 13:30 UTC, swelf19 commented
> > > cmd+shift+F on `lido` still results in several matches particularly in the `./demo/` folder
> > 
> > 
> > as far as i can see its only lido's contracts
> 
> do we need them in the repo? maybe we should move the helpers to the interchain staking repo? this is doubtfully the place for lido contracts: as far as I understand, it's going to become a public neutron daemon repository

yeah, lets remove demo contracts from this repo. I think we can create a standalone repo with general purpose contracts for tests in nearest future

2022-07-08 14:22 UTC, NeverHappened commented
> https://github.com/neutron-org/neutron/pull/15#issuecomment-1178988500

I've added the neutrond to path and it fixed the problem, sry for bothering

2022-07-11 20:16 UTC, foxpy approved these changes

2022-07-11 20:18 UTC, pr0n00gler requested changes

2022-07-11 20:18 UTC, mmikev commented on readme.md
> +neutrond tx interchainqueries register-interchain-query test-2 connection-0 x/staking/DelegatorDelegations '{"delegator": "cosmos1qnk2n4nlkpw9xfqntladh74w6ujtulwn7j8za9"}' 1 --from demowallet1 --gas
Still old cosmos prefixed addresses in readme

2022-07-11 20:20 UTC, foxpy commented on readme.md
> +neutrond tx interchainqueries register-interchain-query test-2 connection-0 x/staking/DelegatorDelegations '{"delegator": "cosmos1qnk2n4nlkpw9xfqntladh74w6ujtulwn7j8za9"}' 1 --from demowallet1 --gas
Actually, `grep -R cosmos1 .` reveals lots of them.

2022-07-12 13:38 UTC, pr0n00gler approved these changes

2022-07-13 12:30 UTC, ratik approved these changes

2022-07-13 13:08 UTC, sotnikov-s approved these changes

2022-07-13 13:24 UTC, NeverHappened approved these changes

2022-07-14 08:16 UTC, merged