feat: updated querySubmittedTransactions request arguments
neutron-org/neutron pull request #20
Opened 2022-07-20 14:36 UTC by swelf19

implements https://p2pvalidator.atlassian.net/jira/software/projects/LSC/boards/121?selectedIssue=LSC-95

Changed query parameters for QuerySubmittedTransactionsRequest.
start-end request params replaced with start-limit request params

2022-07-25 09:58 UTC, foxpy requested changes
`make build` and `make test` fail with `missing go.sum entry` error messages. Please fix this (just run corresponding `go get`'s and commit `go.sum` changes)

2022-07-25 09:58 UTC, foxpy commented on proto/interchainqueries/query.proto
> +  uint64 limit = 3;
I don't think it is a good idea to reuse protobuf sequential number for a different field.

2022-07-25 09:58 UTC, foxpy commented on x/interchainqueries/client/cli/query.go
> +			limit, err := strconv.ParseUint(args[2], 10, 64)
That doesn't look like an optional argument. Or do you imply `limit=0` being an unset limit? That's odd.

2022-07-25 09:58 UTC, foxpy commented on x/interchainqueries/keeper/keeper.go
> +		limit = 100
But there is a constant `x/interchainqueries/keeper.DEFAULT_SUBMITTED_TRANSACTIONS_LIMIT`

2022-07-25 09:58 UTC, foxpy commented on x/interchainqueries/keeper/keeper_test.go
> +	start = 3
Please set a limit here, too, just for clarity
```suggestion
	start, limit = 3, 5
```

2022-07-25 10:02 UTC, mmikev commented on proto/interchainqueries/query.proto
> +  uint64 limit = 3;
Why? We are in active development, it's totally ok I think.

But we definitely can't do that so freely after release because it will break backward compatibility

2022-07-25 10:02 UTC, foxpy commented on proto/interchainqueries/query.proto
> +  uint64 limit = 3;
:thinking: okay, you are right

2022-07-26 07:57 UTC, zavgorodnii commented
i think what we call `start, limit` is usually called `offset, limit`?

2022-07-26 07:59 UTC, zavgorodnii commented on x/interchainqueries/keeper/keeper.go
> +	DEFAULT_SUBMITTED_TRANSACTIONS_LIMIT   = 100
I don't think that Go uses all caps snake case for constants : ) looks like you've been coding in Rust lately hehe

2022-07-27 07:42 UTC, sotnikov-s requested changes

2022-07-27 07:42 UTC, sotnikov-s commented on x/interchainqueries/keeper/keeper.go
> +	if limit == 0 {
the whole limit validation and normalisation can be simplified to:
```go
switch {
case limit == 0:
	limit = DEFAULT_SUBMITTED_TRANSACTIONS_LIMIT
case limit > MAX_SUBMITTED_TRANSACTIONS_QUERY_LIMIT:
	return nil, sdkerrors.Wrapf(sdkerrors.ErrInvalidRequest, "failed to query submitted transactions, max query limit %d, got %d", MAX_SUBMITTED_TRANSACTIONS_QUERY_LIMIT, limit)
}
```
(with consts camelCased ofc)

2022-07-27 07:42 UTC, sotnikov-s commented on x/interchainqueries/keeper/keeper.go
>  // GetSubmittedTransactions returns a list of transactions from start ID to end ID
it's end ID in the comment still. please update

2022-07-27 07:42 UTC, sotnikov-s commented on x/interchainqueries/client/cli/query.go
> +			limit, err := strconv.ParseUint(args[2], 10, 64)
maybe a --limit flag would be better? looks like a way to make optional parameters for cli

2022-07-28 07:42 UTC, closed without merging