feat: tx query result callback
neutron-org/neutron pull request #21
Opened 2022-07-20 16:18 UTC by zavgorodnii

This PR introduces a lot of changes:

1. The `SudoTxQueryResult()` callback is added. This callback is executed when a transaction result is submitted (unconditionally, every time);
2. Results for Tx queries **are not saved to state anymore**. Only the fact that a certain result (query_id + tx_hash) was submitted is saved, and duplicate results **are discarded without an error**;
3. Everything related to `QueryTransactions()` was removed.

**HOW TO TEST THIS CODE?**

Please have a look at this PR: https://github.com/neutron-org/neutron-contracts/pull/6
You can find the instructions in the readme: https://github.com/neutron-org/neutron-contracts/blob/feat/check-tx-query-result-callback/contracts/neutron_interchain_queries/README.md

**UPD:**

After a long discussion with @pr0n00gler we decided to limit the max number of transactions per submission to exactly 1.

Please re-review this PR, and please note that you now have to test it with this version of the relayer: https://github.com/neutron-org/cosmos-query-relayer/pull/16

2022-07-27 16:57 UTC, pr0n00gler requested changes
Keeper's methods `GetLastSubmittedTransactionIDForQuery` and `SetLastSubmittedTransactionIDForQuery` are unused now because of removed tx logic. Let's remove them too

2022-07-27 16:57 UTC, mmikev commented on x/interchainqueries/keeper/keeper.go
> +// SaveTransactionAsSubmitted simply stores a key (SubmittedTxKey + bigEndianBytes(queryID) + bigEndianBytes(txID)) with
We don't have txID anymore

2022-07-27 16:57 UTC, mmikev commented on x/interchainqueries/keeper/keeper.go
> +	return len(store.Get(key)) > 0
Why not `return store.Has(key)`?

2022-07-27 16:59 UTC, foxpy commented
FYI: there is a typo in branch name :ghost:

2022-07-27 17:05 UTC, zavgorodnii commented on x/interchainqueries/keeper/keeper.go
> +	return len(store.Get(key)) > 0
lol true.

2022-07-27 17:05 UTC, zavgorodnii commented
> FYI: there is a typo in branch name 👻

chachlo popyachtsa

2022-07-28 09:49 UTC, mmikev commented on x/interchainqueries/keeper/process_block_results.go
> +			if _, err := k.sudoHandler.SudoTxQueryResult(ctx, queryOwner, queryID, tmHeader.Header.Height, tx.Data); err != nil {
What do you think about calling sudo once for the whole block (batch of txs), not for each transaction every time?

2022-07-28 10:13 UTC, zavgorodnii commented on x/interchainqueries/keeper/process_block_results.go
> +			if _, err := k.sudoHandler.SudoTxQueryResult(ctx, queryOwner, queryID, tmHeader.Header.Height, tx.Data); err != nil {
what would be the benefit?

2022-07-28 10:20 UTC, mmikev commented on x/interchainqueries/keeper/process_block_results.go
> +			if _, err := k.sudoHandler.SudoTxQueryResult(ctx, queryOwner, queryID, tmHeader.Header.Height, tx.Data); err != nil {
Gas consumption would be less.
Every wasm handler (Execute, [Sudo](https://github.com/CosmWasm/wasmd/blob/d63bea442bedf5b3055f3821472c7e6cafc3d813/x/wasm/keeper/keeper.go#L460), Migrate) instantiates a contract code on every call and consumes gas for such setup (unless contact's code is not pinned into wasmvm cache). As well as other micro reads from the storage

2022-07-28 13:23 UTC, foxpy commented on x/interchainqueries/keeper/process_block_results.go
> +			if _, err := k.sudoHandler.SudoTxQueryResult(ctx, queryOwner, queryID, tmHeader.Header.Height, tx.Data); err != nil {
Though that would require a sane limit for amount of transactions per batch.

2022-07-28 17:32 UTC, zavgorodnii commented on x/interchainqueries/keeper/process_block_results.go
> +			if _, err := k.sudoHandler.SudoTxQueryResult(ctx, queryOwner, queryID, tmHeader.Header.Height, tx.Data); err != nil {
After a long discussion with @pr0n00gler we decided to limit the max number of transactions per submission to exactly 1.

Please re-review this PR, and please note that you now have to test it with this version of the relayer: https://github.com/neutron-org/cosmos-query-relayer/pull/16

2022-07-29 07:36 UTC, quasisamurai commented on x/interchainqueries/keeper/msg_server.go
> +			ctx.Logger().Error("SubmitQueryResult: failed to UnpackConsensusState",
should we log err here? (and in the rest ctx.Logger().Debug calls)

2022-07-29 07:39 UTC, zavgorodnii commented on x/interchainqueries/keeper/msg_server.go
> +			ctx.Logger().Error("SubmitQueryResult: failed to UnpackConsensusState",
yes,  because resp.ConsensusState was retrieved from ibc keeper (internal module, 100% should return a valid response if the error is nil) without an error

2022-07-29 11:55 UTC, swelf19 reviewed
x/interchainqueries/types/keys.go L44 and L60 dead code.

2022-07-29 13:06 UTC, sotnikov-s commented on internal/sudo/sudo.go
> +type SudoMessageTxQueryResult struct {
let's start making comments for everything that we write/touch in some way? thus we will smoothly decrease the size of uncommented code. anyway we will have to do it. this is a great way to accomplish good comments coverage without hating it

2022-07-29 13:06 UTC, sotnikov-s commented on internal/sudo/sudo.go
> +// to check whether the transaction actually satisfies the initial query arguments.
> to check whether the transaction actually satisfies the initial query arguments

is it outdated or something? this is not the only reason of using the SudoTxQueryResult, is it? e.g. later at the place you execute this method you say `Let the query owner contract process the query result`

2022-07-29 13:06 UTC, sotnikov-s commented on x/interchainqueries/keeper/keeper.go
> +	key := types.GetSubmittedTransactionIDForQueryKey(queryID, txHash)
what's the point of having query_id as a part of the key? hash is unique and it guarantees no collisions. also, different interchain queries may be subscribed on the same address deposits, so having the query_id will result in having duplications of transactions saved as processed

2022-07-29 13:06 UTC, sotnikov-s commented on x/interchainqueries/keeper/keeper.go
> +	store.Set(key, []byte{1})
[]byte{} is also applicable and it can save a couple of bytes :)

2022-07-29 13:06 UTC, sotnikov-s commented on x/interchainqueries/keeper/process_block_results.go
> +// ProcessBlock verifies headers and transaction in the block
please update the description with the new functionality you've introduced

2022-07-29 13:06 UTC, sotnikov-s commented on x/interchainqueries/keeper/process_block_results.go
> +		ctx.Logger().Debug("ProcessBlock: failed to cast current header to tendermint Header", "query_id", queryID)
shouldn't fails in case of this conversion and the one below be logged on the error level?

2022-07-29 13:11 UTC, swelf19 commented on x/interchainqueries/keeper/keeper.go
> +	key := types.GetSubmittedTransactionIDForQueryKey(queryID, txHash)
Multiple queries/contracts cat get the tx as a result to own query. Composite key (queryID, txHash) guarantees that every recipient get tx in sudo callback

2022-07-29 13:51 UTC, zavgorodnii commented on x/interchainqueries/keeper/keeper.go
> +	store.Set(key, []byte{1})
i was wondering whether anyone will notice : )

2022-07-29 13:53 UTC, zavgorodnii commented on x/interchainqueries/keeper/process_block_results.go
> +		ctx.Logger().Debug("ProcessBlock: failed to cast current header to tendermint Header", "query_id", queryID)
don't think so. the block here comes directly from msg.Result.Block, which can contain all sorts of erroneous data

2022-07-29 15:53 UTC, sotnikov-s approved these changes

2022-08-01 08:00 UTC, swelf19 approved these changes

2022-08-01 08:52 UTC, pr0n00gler approved these changes

2022-08-01 08:53 UTC, merged