feat: custom message encoder
neutron-org/neutron pull request #22
Opened 2022-07-21 04:38 UTC by foxpy

Assigned task: [LSC-79](https://p2pvalidator.atlassian.net/browse/LSC-79).

What is done:
- added custom message binding types;
- implemented dispatching of custom messages;
- implemented a unit test (checks that message decodes and executes by node) per custom message.

2022-07-21 04:43 UTC, foxpy commented on wasmbinding/bindings/msg.go
> +	Msgs [][]byte `json:"msgs"`
XXX: I should probably go with array of protobuf messages here? I don't like the idea of having protobuf messages in JSON.

2022-07-21 04:43 UTC, foxpy commented on wasmbinding/message_plugin.go
> +	}
FIXME: where do I obtain this account ID from?

2022-07-21 04:43 UTC, foxpy commented on wasmbinding/message_plugin.go
> +	//             tx.Msgs += msg.to_any()
TODO: this one really depends on a previous question about incoming protobuf messages in `wasmbinding.MsgSubmitTx`.

2022-07-21 04:43 UTC, foxpy commented on wasmbinding/message_plugin.go
> +	_ = txResponse // TODO: transaction response is probably supposed to be used?
TODO: any suggestions?

2022-07-21 07:31 UTC, swelf19 commented on wasmbinding/bindings/msg.go
> +	Msgs [][]byte `json:"msgs"`
the main goal of all these  "get rid of stargate" tasks is actually "get rid of protobuf", so answer is "no, you should not" from my point of view.

2022-07-21 07:41 UTC, pr0n00gler requested changes

2022-07-21 07:41 UTC, mmikev commented on wasmbinding/bindings/msg.go
> +	Owner        string `json:"owner"`
We don't have `owner` anymore. We have `interchainAccountID` instead

2022-07-21 07:41 UTC, mmikev commented on wasmbinding/bindings/msg.go
> +	Msgs [][]byte `json:"msgs"`
`[]*types.Any`

2022-07-21 07:41 UTC, mmikev commented on wasmbinding/bindings/msg.go
> +	Owner        string `json:"owner"`
And `FromAddress` is the sender of the message, not an address on remote chain

2022-07-21 07:41 UTC, mmikev commented on wasmbinding/message_plugin.go
> +	// FIXME: msg.InterchainAccountId is definitely not supposed to be left empty
See comment above about `owner` and `interchainAccountID`

2022-07-21 07:41 UTC, mmikev commented on wasmbinding/bindings/msg.go
> +	Owner        string `json:"owner"`
This structure implies that any contract calls the `MsgSubmitMsg` and can set `FromAddress` to any value. This is wrong, `FromAddress` must be equal to the caller of the msg, in our case it must be set to the `contractAddress` in your encoder. `InterchainAccountID` on other side can be set to any value by user/contract.

2022-07-21 07:41 UTC, mmikev commented on wasmbinding/message_plugin.go
> +	_ = txResponse // TODO: transaction response is probably supposed to be used?
Make a binding for this value and return it

2022-07-21 07:45 UTC, mmikev commented on wasmbinding/message_plugin.go
> +	}
https://github.com/neutron-org/neutron/pull/22#discussion_r926343174

2022-07-21 07:45 UTC, mmikev commented on wasmbinding/message_plugin.go
> +	//             tx.Msgs += msg.to_any()
https://github.com/neutron-org/neutron/pull/22#discussion_r926345148

2022-07-21 07:47 UTC, mmikev commented on wasmbinding/bindings/msg.go
> +	Msgs [][]byte `json:"msgs"`
> the main goal of all these "get rid of stargate" tasks is actually "get rid of protobuf"

I do not agree. If we want to send interchain txs, we have to use profobug. There is no other way. Or do you have something in mind?

2022-07-22 12:07 UTC, foxpy commented on wasmbinding/bindings/msg.go
> +	Owner        string `json:"owner"`
> `InterchainAccountID` on other side can be set to any value by user/contract.

Does that mean I have to expose this field to contracts through my binding?

2022-07-22 12:42 UTC, mmikev commented on wasmbinding/bindings/msg.go
> +	Owner        string `json:"owner"`
Yes

2022-07-25 06:52 UTC, foxpy commented on wasmbinding/bindings/msg.go
> +	Msgs [][]byte `json:"msgs"`
Switched to `[]*types.Any`

2022-07-25 06:53 UTC, foxpy commented on wasmbinding/message_plugin.go
> +	_ = txResponse // TODO: transaction response is probably supposed to be used?
Well, I have done that, but there are two concerning caveats:
- this value is literally an empty struct;
- I don't use returned value anywhere further.

2022-08-01 20:14 UTC, foxpy commented on wasmbinding/test/custom_message_test.go
> +	events, data, err = messenger.DispatchMsg(ctx, contractAddr, ibcStruct.Path.EndpointA.ChannelConfig.PortID, types.CosmosMsg{
This test fails here and I have no idea how to fix it:

```
--- FAIL: TestSubmitTx (0.17s)
    custom_message_test.go:173: 
                Error Trace:    custom_message_test.go:173
                Error:          Received unexpected error:
                            
                                github.com/neutron-org/neutron/x/interchaintxs/keeper.Keeper.SubmitTx
                                        /home/foxpy/Work/neutron/x/interchaintxs/keeper/msg_server.go:67
                                github.com/neutron-org/neutron/wasmbinding.PerformSubmitTx
                                        /home/foxpy/Work/neutron/wasmbinding/message_plugin.go:75
                                github.com/neutron-org/neutron/wasmbinding.(*CustomMessenger).submitTx
                                        /home/foxpy/Work/neutron/wasmbinding/message_plugin.go:55
                                github.com/neutron-org/neutron/wasmbinding.(*CustomMessenger).DispatchMsg
                                        /home/foxpy/Work/neutron/wasmbinding/message_plugin.go:42
                                github.com/neutron-org/neutron/wasmbinding/test.TestSubmitTx
                                        /home/foxpy/Work/neutron/wasmbinding/test/custom_message_test.go:170
                                perform submit interchain tx: submit interchaintx: failed to GetActiveChannelID for port icacontroller-neutron15fv4jxqgfctgsgcd4w3j5plzpd7gleprte7vls.test_interchain_account_id: no active channel for this owner
```

2022-08-01 21:08 UTC, pr0n00gler requested changes

2022-08-01 21:08 UTC, mmikev commented on wasmbinding/message_plugin.go
> +	Ictx         ictxkeeper.Keeper
Let's use here `MsgServer` too instead of keeper

2022-08-01 21:08 UTC, mmikev commented on wasmbinding/bindings/msg.go
> +	Msgs                []KVKey `json:"msgs"`
Huh? `KVKey`?

2022-08-01 21:08 UTC, mmikev commented on wasmbinding/message_plugin.go
> +			return nil, nil, sdkerrors.Wrap(err, "neutron msg")
A bit more clear error message please

2022-08-01 21:08 UTC, mmikev commented on wasmbinding/message_plugin.go
> +		return nil, nil, sdkerrors.Wrap(err, "perform submit interchain tx")
A bit more clear error message please

2022-08-01 21:08 UTC, mmikev commented on wasmbinding/message_plugin.go
> +		return nil, sdkerrors.Wrap(err, "submit interchaintx")
A bit more clear error message please

2022-08-01 21:08 UTC, mmikev commented on wasmbinding/message_plugin.go
> +		return nil, nil, sdkerrors.Wrap(err, "perform register interchain account")
A bit more clear error message please

2022-08-01 21:08 UTC, mmikev commented on wasmbinding/message_plugin.go
> +		return nil, nil, sdkerrors.Wrap(err, "perform register interchain query")
A bit more clear error message please

2022-08-01 21:08 UTC, mmikev commented on wasmbinding/message_plugin.go
> +		return nil, sdkerrors.Wrap(err, "register interchain query")
A bit more clear error message please

2022-08-02 03:31 UTC, foxpy commented on wasmbinding/message_plugin.go
> +	Ictx         ictxkeeper.Keeper
done.

why is API duplicated like this, by the way?

2022-08-02 03:33 UTC, foxpy commented on wasmbinding/bindings/msg.go
> +	Msgs                []KVKey `json:"msgs"`
Renamed to `ProtobufAny` for clarity

2022-08-02 03:39 UTC, foxpy commented
@pr0n00gler I have clarified error messages, though I guess you would still not like the new ones? You are free to submit suggestions because I don't have any more ideas.

2022-08-02 03:52 UTC, foxpy commented on wasmbinding/test/custom_message_test.go
> +	// TODO: observe side effects?
Aside from these TODOs (which, at the moment, I have absolutely no idea how to resolve them), PR looks fine. Should I move it into review stage?

2022-08-02 06:59 UTC, mmikev commented on wasmbinding/test/custom_message_test.go
> +	// TODO: observe side effects?
Sure

2022-08-02 15:43 UTC, pr0n00gler requested changes

2022-08-02 15:43 UTC, mmikev commented on wasmbinding/bindings/msg.go
> +// Owner is address on local chain, FromAddress is address on remote chain.
Outdated comment

2022-08-02 15:43 UTC, mmikev commented on wasmbinding/message_plugin.go
> +			ctx.Logger().Debug("failed to decode incoming custom message from", contractAddr.String())
`Debug()` accepts msg as first argument and `keyvals ...interface{}` for the rest arguments. So you forgot to pass a key here

2022-08-02 15:43 UTC, mmikev commented on wasmbinding/message_plugin.go
> +		ctx.Logger().Info(contractAddr.String(), "fail marshal json", "error", err)
I think you mixed up here log msg and keys (`contractAddr.String()` should be as second argument, right?)

2022-08-03 07:39 UTC, mmikev commented on wasmbinding/message_plugin.go
> +	Ictx         ictxkeeper.Keeper
Didn't get you. What do you mean by duplicated?

2022-08-03 07:54 UTC, foxpy commented on wasmbinding/message_plugin.go
> +	Ictx         ictxkeeper.Keeper
Okay, I made wrong assumptions and this question makes zero sense.

Can we now close this thread?

2022-08-03 08:32 UTC, swelf19 commented on wasmbinding/message_plugin.go
> +		ctx.Logger().Debug(contractAddr.String(), "json.Marshal: failed to marshal submitTx response to JSON",
Did toy test the error/info messages? the struct looks wrong. According to the method signature, only the first argument is "info msg", starting from the second its a key-values pairs. In this case pair looks like {submitTx.ConnectionId,"interchain_account_id"}

2022-08-03 08:33 UTC, foxpy commented on wasmbinding/message_plugin.go
> +		ctx.Logger().Debug(contractAddr.String(), "json.Marshal: failed to marshal submitTx response to JSON",
Crap, I have completely missed this one

2022-08-03 08:34 UTC, mmikev commented on wasmbinding/message_plugin.go
> +		ctx.Logger().Debug(contractAddr.String(), "json.Marshal: failed to marshal submitTx response to JSON",
Yep, that's what I commented about [here](https://github.com/neutron-org/neutron/pull/22#discussion_r935752903) but accidentally marked the comment as resolved

2022-08-03 08:35 UTC, foxpy commented on wasmbinding/message_plugin.go
> +		ctx.Logger().Debug(contractAddr.String(), "json.Marshal: failed to marshal submitTx response to JSON",
And other ones as well. I will toy test each log print and return here when I am done

2022-08-03 08:58 UTC, foxpy commented on wasmbinding/message_plugin.go
> +		ctx.Logger().Debug(contractAddr.String(), "json.Marshal: failed to marshal submitTx response to JSON",
Calls to logger are looking like they are in a good shape now.

2022-08-03 09:14 UTC, pr0n00gler requested changes

2022-08-03 09:14 UTC, mmikev commented on wasmbinding/message_plugin.go
> +	response, err := m.Ictxmsgserver.SubmitTx(sdk.WrapSDKContext(ctx), &tx)
I suggest to call `tx.ValidateBasic()` before calling msgserver handler to do a basic validity checks for the msg

2022-08-03 09:14 UTC, mmikev commented on wasmbinding/message_plugin.go
> +	response, err := m.Ictxmsgserver.SubmitTx(sdk.WrapSDKContext(ctx), &tx)
And do that for every msg obviously, not only `MsgSubmitTx`

2022-08-03 13:19 UTC, pr0n00gler submitted a review, later dismissed

2022-08-03 15:57 UTC, ratik submitted a review, later dismissed

2022-08-03 19:43 UTC, zavgorodnii submitted a review, later dismissed
https://github.com/neutron-org/neutron-contracts/pull/7#pullrequestreview-1060912816

2022-08-03 20:34 UTC, pr0n00gler requested changes

2022-08-03 20:34 UTC, mmikev commented on app/app.go
> +	wasmOpts = append(wasmbinding.RegisterCustomPlugins(&app.InterchainTxsKeeper, &app.InterchainQueriesKeeper, &app.InterchainTxsKeeper), wasmOpts...)
You pass `InterchainTxsKeeper` twice as first and third argument

2022-08-03 20:34 UTC, mmikev commented on wasmbinding/wasm.go
>  	icacontrollerkeeper "github.com/neutron-org/neutron/x/interchaintxs/keeper"
Your `icacontrollerkeeper` actually is interchaintxs keeper. That's why there is no error in `RegisterCustomPlugins` when you pass `app.InterchainTxsKeeper` as first argument because it's literally the same structure

2022-08-04 07:16 UTC, zavgorodnii submitted a review, later dismissed

2022-08-04 07:23 UTC, zavgorodnii requested changes

2022-08-04 07:23 UTC, zavgorodnii commented on wasmbinding/message_plugin.go
> +	ctx.Logger().Info("registered interchain account",
this is 100% debug

2022-08-04 07:23 UTC, zavgorodnii commented on wasmbinding/message_plugin.go
> +	}
please add \n after processing an error

2022-08-04 07:23 UTC, zavgorodnii commented on wasmbinding/message_plugin.go
> +	ctx.Logger().Info("registered interchain query",
debug

2022-08-04 07:23 UTC, zavgorodnii commented on wasmbinding/message_plugin.go
> +	}
\n, and please add \n's in all similar places

2022-08-04 07:23 UTC, zavgorodnii commented on wasmbinding/message_plugin.go
> +	ctx.Logger().Info("interchain transaction submitted",
debug

2022-08-04 08:37 UTC, pr0n00gler approved these changes

2022-08-04 08:40 UTC, zavgorodnii approved these changes

2022-08-04 08:52 UTC, merged