Feat: improve kv results security
neutron-org/neutron pull request #25
Opened 2022-07-26 09:15 UTC by pr0n00gler

Task - https://p2pvalidator.atlassian.net/jira/software/projects/LSC/boards/121?selectedIssue=LSC-102

What's changed:
* instead of just query type, user must provide exact KV keys he wants to read from remote chain's storage.
* Neutron checks that all requested keys are provided in submitted result;
* Neutron verifies non-existence of some keys with Merkle Proofs.

Depends on: https://github.com/neutron-org/cosmos-query-relayer/pull/12

2022-07-28 10:19 UTC, zavgorodnii commented on proto/interchainqueries/genesis.proto
> +  string transactions_filter = 5;
just a note — this affects our https://github.com/neutron-org/neutron-contracts examples heavily, we should make sure that everything is updated on that side

2022-07-28 10:22 UTC, mmikev commented on proto/interchainqueries/genesis.proto
> +  string transactions_filter = 5;
Yeah, if I got your comment correctly, the examples will be updated after CustomEncoders and CustomQueries are implemented as well as smart-contract's part of the task

2022-07-28 10:22 UTC, zavgorodnii commented on readme.md
> +neutrond tx interchainqueries register-interchain-query test-2 connection-0 5 kv staking/311404eca9d67fb05c5324135ffadbfaaed724be7dd31404eca9d67fb05c5324135ffadbfaaed724be7dd3 --from demowallet1 --ga
This shit looks scary af:

```
staking/311404eca9d67fb05c5324135ffadbfaaed724be7dd31404eca9d67fb05c5324135ffadbfaaed724be7dd3
```

With this implementation is absolutely crucial to provide as many standard query implementations as possible in our contracts repo.

2022-07-28 10:23 UTC, mmikev commented on readme.md
> +neutrond tx interchainqueries register-interchain-query test-2 connection-0 5 kv staking/311404eca9d67fb05c5324135ffadbfaaed724be7dd31404eca9d67fb05c5324135ffadbfaaed724be7dd3 --from demowallet1 --ga
The tutorial how to obtain the key is already in the readme, look closely

2022-07-28 10:29 UTC, zavgorodnii commented on x/interchainqueries/client/cli/tx.go
> +				txFilter = queryData
can we add a check of some sort here? i mean, if it's a txFilter, we simply save the data as is, and it might be something like `(*&6f3ob` by mistake

2022-07-28 10:32 UTC, zavgorodnii commented on x/interchainqueries/types/types.go
> +	splittedString := strings.Split(s, pathKeyDelimiter)
split

2022-07-28 10:39 UTC, zavgorodnii commented on readme.md
> +neutrond tx interchainqueries register-interchain-query test-2 connection-0 5 kv staking/311404eca9d67fb05c5324135ffadbfaaed724be7dd31404eca9d67fb05c5324135ffadbfaaed724be7dd3 --from demowallet1 --ga
yup, i updated the comment, sorry

2022-07-28 11:09 UTC, mmikev commented on x/interchainqueries/types/types.go
> +	splittedString := strings.Split(s, pathKeyDelimiter)
fixed

2022-07-28 11:09 UTC, mmikev commented on x/interchainqueries/client/cli/tx.go
> +				txFilter = queryData
fixed

2022-07-29 11:01 UTC, zavgorodnii submitted a review, later dismissed
tested locally, no problems detected

2022-07-29 13:27 UTC, ratik commented on readme.md
> +foo@bar % neutrond debug addr neutron1qnk2n4nlkpw9xfqntladh74w6ujtulwn6dwq8z
```suggestion
foo@bar % neutrond debug addr neutronvaloper1qnk2n4nlkpw9xfqntladh74w6ujtulwnqshepx
```

2022-08-01 14:26 UTC, zavgorodnii submitted a review, later dismissed

2022-08-02 13:51 UTC, ratik submitted a review, later dismissed
LGTM. tested and it worked
but please update readme, remove query-transactions-search-result item

2022-08-03 18:21 UTC, foxpy commented
ping @pr0n00gler conflicts again :ghost:

2022-08-09 08:27 UTC, sotnikov-s commented on x/interchainqueries/types/genesis.pb.go
> +type KVKey struct {
seems you haven't generated the code after introducing comments to the KVKey message. this is my diff after running `ignite generate proto-go`

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/34917380/183452877-375a0057-3e68-45d5-8bdd-ce0bc882b867.png">

2022-08-09 08:27 UTC, sotnikov-s commented on proto/interchainqueries/genesis.proto
> -  // The unique id of the registered query.
such a beauty comment, must have been introduced by someone who's really proficient in inglesh. this one and the other ones below. please consider using the current comments

2022-08-09 13:01 UTC, NeverHappened commented on wasmbinding/bindings/query.go
>  	// The query type identifier (i.e. /cosmos.staking.v1beta1.Query/AllDelegations).
probably should change that comment as well

2022-08-09 13:55 UTC, sotnikov-s commented on x/interchainqueries/client/cli/tx.go
> +			if queryType.IsTX() {
switch would be prettier here

2022-08-09 13:55 UTC, sotnikov-s commented on x/interchainqueries/keeper/msg_server.go
> +				return nil, sdkerrors.Wrap(types.ErrInvalidProof, "unknown proof type")
might be enhanced like:
```go
return nil, sdkerrors.Wrapf(types.ErrInvalidProof, "unknown proof type %T", proof.GetProofs()[0].GetProof())
```

2022-08-09 13:55 UTC, sotnikov-s commented on x/interchainqueries/keeper/msg_server.go
> +				return nil, sdkerrors.Wrapf(types.ErrInvalidSubmittedResult, "KV key from result is not equal to registered query key: %v != %v", result.Key, query.Keys[index].Key)
since the key field is a `[]byte`, using `%v` logging will be poor here:
https://goplay.space/#6F30LkuQNNJ

2022-08-09 14:14 UTC, mmikev commented on x/interchainqueries/keeper/msg_server.go
> +				return nil, sdkerrors.Wrapf(types.ErrInvalidSubmittedResult, "KV key from result is not equal to registered query key: %v != %v", result.Key, query.Keys[index].Key)
What are you suggesting? hex?

2022-08-09 14:19 UTC, sotnikov-s commented on x/interchainqueries/keeper/msg_server.go
> +				return nil, sdkerrors.Wrapf(types.ErrInvalidSubmittedResult, "KV key from result is not equal to registered query key: %v != %v", result.Key, query.Keys[index].Key)
no, I'm suggesting using `%s` just as I demonstrated by the link

2022-08-09 15:25 UTC, mmikev commented on x/interchainqueries/keeper/msg_server.go
> +				return nil, sdkerrors.Wrapf(types.ErrInvalidSubmittedResult, "KV key from result is not equal to registered query key: %v != %v", result.Key, query.Keys[index].Key)
Key slice cannot be converter into string type because it usually contains non-text bytes. So I suggest leave it as it as

2022-08-09 15:26 UTC, mmikev commented on x/interchainqueries/client/cli/tx.go
> +			if queryType.IsTX() {
Fixed

2022-08-09 15:26 UTC, mmikev commented on x/interchainqueries/keeper/msg_server.go
> +				return nil, sdkerrors.Wrap(types.ErrInvalidProof, "unknown proof type")
Fixed

2022-08-09 17:23 UTC, NeverHappened reviewed
LGTM, I commented about a few typos here and there

2022-08-09 17:23 UTC, NeverHappened commented on x/interchainqueries/client/cli/tx.go
> +		Use:     "register-interchain-query [zone-id] [connection-id] [update-period] [query_type] [query_data]",
typo: `[query-type] [query-data]`)

2022-08-09 17:23 UTC, NeverHappened commented on x/interchainqueries/keeper/keeper_test.go
> +				//suite.NoError(suite.Path.EndpointB.UpdateClient())
why commented?

2022-08-09 17:23 UTC, NeverHappened commented on x/interchainqueries/keeper/msg_server.go
> +			switch proof.GetProofs()[0].GetProof().(type) {
Maybe comment with `We take the first proof to fetch type, but still use whole proof for a check` (not sure)

2022-08-09 17:23 UTC, NeverHappened commented on x/interchainqueries/keeper/msg_server.go
> +				if err := proof.VerifyNonMembership(ibccommitmenttypes.GetSDKSpecs(), consensusState.GetRoot(), path); err != nil {
Maybe comment something like `if smart contract requested non existent key, we proof non existance too`

2022-08-09 17:23 UTC, NeverHappened commented on x/interchainqueries/keeper/keeper_test.go
> +	// TestVersion defines a reusable interChainAccounts version string for testing purposes
i think we always write `interchain` without upcase like `interchainAccounts`

2022-08-10 07:16 UTC, sotnikov-s commented on x/interchainqueries/keeper/msg_server.go
> +				return nil, sdkerrors.Wrapf(types.ErrInvalidSubmittedResult, "KV key from result is not equal to registered query key: %v != %v", result.Key, query.Keys[index].Key)
yeah, understandable, thanks for explanation

2022-08-10 08:01 UTC, sotnikov-s commented on x/interchainqueries/types/types.go
> +	kvKeysDelimiter  = ","
please note that:
1. imo it'd be better to have the same namings for these constants as we have in neutron contracts
2. the delimiter is different from the one defined in the neutron contracts
https://github.com/neutron-org/neutron-contracts/blob/feat/kv-improvements/packages/bindings/src/types.rs#L101

2022-08-10 10:21 UTC, sotnikov-s commented on readme.md
> +4. Now we can compose a full KV key for to get a delegation (we don't `0x` prefix in hex values):
misprint: Now we can compose a full KV key **for to** get a delegation

2022-08-10 11:10 UTC, zavgorodnii commented
just ran the `test_*.sh` tests in `neutron-contracts`, everything seems to work. reading the code now

2022-08-10 11:17 UTC, NeverHappened requested changes
There is a small issue: when trying to get result with query_id that does not exist `./build/neutrond query interchainqueries query-result 1 --node tcp://127.0.0.1:16657`, we get error (output below), but probably should just get "query with such id does not exist" result

```
Error: rpc error: code = InvalidArgument desc =
github.com/cosmos/cosmos-sdk/baseapp.gRPCErrorToSDKError
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:590
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:579
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:421
github.com/tendermint/tendermint/abci/client.(*localClient).QuerySync
	github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:256
github.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync
	github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:159
github.com/tendermint/tendermint/rpc/core.ABCIQuery
	github.com/tendermint/tendermint@v0.34.19/rpc/core/abci.go:20
reflect.Value.call
	reflect/value.go:543
reflect.Value.Call
	reflect/value.go:339
github.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_json_handler.go:96
github.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_json_handler.go:122
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2046
net/http.(*ServeMux).ServeHTTP
	net/http/server.go:2424
github.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_server.go:236
github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_server.go:209
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2046
net/http.serverHandler.ServeHTTP
	net/http/server.go:2878
net/http.(*conn).serve
	net/http/server.go:1929
failed to get query result by query id: no query result: no query result: invalid request
Usage:
  neutrond query interchainqueries query-result [query-id] [flags]

Flags:
      --height int      Use a specific height to query state at (this can error if the node is pruning state)
  -h, --help            help for query-result
      --node string     <host>:<port> to Tendermint RPC interface for this chain (default "tcp://localhost:26657")
  -o, --output string   Output format (text|json) (default "text")

Global Flags:
      --chain-id string     The network chain ID
      --home string         directory for config and data (default "/Users/nhpd/.neutrond")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors
```

2022-08-10 12:41 UTC, sotnikov-s commented on x/interchainqueries/keeper/msg_server.go
> +					ctx.Logger().Debug("ProcessBlock: failed to SudoKVQueryResult",
ctx.Logger().Debug("**ProcessBlock**: failed to SudoKVQueryResult << we're not in the ProcessBlock, we're in the SubmitQueryResult

2022-08-10 12:55 UTC, zavgorodnii commented on x/interchainqueries/keeper/keeper.go
> +func (k Keeper) isRegisteredQueryExist(ctx sdk.Context, id uint64) bool {
for the love of god, please rename this to `checkQueryExists()` or something

2022-08-10 13:10 UTC, zavgorodnii approved these changes

2022-08-10 13:15 UTC, sotnikov-s approved these changes
reviewed and tested put together with the other related branches — works fine

2022-08-10 13:52 UTC, NeverHappened approved these changes

2022-08-10 15:59 UTC, merged