maintain dependencies
neutron-org/neutron pull request #266
Opened 2023-06-07 16:56 UTC by faddat

Over time, dependencies can go out of date, this fixes several.

2023-06-10 05:14 UTC, foxpy requested changes

2023-06-10 05:14 UTC, foxpy commented on go.mod
> +	github.com/cosmos/cosmos-sdk => github.com/cosmos/cosmos-sdk v0.45.16-ics
this comment is clearly outdated and it makes zero sense here
```suggestion
	github.com/cosmos/cosmos-sdk => github.com/cosmos/cosmos-sdk v0.45.16-ics
```

2023-06-15 11:49 UTC, foxpy approved these changes
I guess we can merge this safely right now

https://github.com/neutron-org/neutron-tests/actions/runs/5277720925

2023-06-25 03:50 UTC, faddat commented
Yep, should be fine.  Afaik, main doesn't represent the current releases.

2023-08-03 13:03 UTC, pr0n00gler commented
Thanks for your contributing! 
But since the PR is pretty outdated, there a couple of conflicts (some dependencies were already updated and the rest will be updated in https://github.com/neutron-org/neutron/pull/268), i'll close it

2023-08-03 13:03 UTC, closed without merging