feat: add more config/client.toml values #ntrn-529
neutron-org/neutron pull request #272
Opened 2023-06-22 12:15 UTC by NeverHappened

implements #ntrn-529

2023-06-30 11:53 UTC, pr0n00gler submitted a review, later dismissed

2023-06-30 18:28 UTC, foxpy commented on config/config.toml
> +moniker = "Dmitrys-MacBook-Pro.local"
I think this file (and all others in `config/` folder?) has been included by a mistake?

2023-07-04 10:54 UTC, pr0n00gler submitted a review, later dismissed

2023-07-04 13:06 UTC, foxpy submitted a review, later dismissed

2023-07-06 08:16 UTC, sotnikov-s commented on cmd/neutrond/config.go
> +		return fmt.Errorf("couldn't get client config: %v", err)
we usually use %w for returned errors. please stick with this pattern

2023-07-06 08:16 UTC, sotnikov-s commented on cmd/neutrond/config.go
> +			return err
please describe all errors we return

2023-07-06 08:16 UTC, sotnikov-s commented on cmd/neutrond/config.go
> +		panic("could not execute config command")
as a user I'd like to see the reason for it which seems to be too many arguments: 2 expected

2023-07-06 08:16 UTC, sotnikov-s commented on cmd/neutrond/root.go
> +		panic(err)
I'd like to see the detailed reason of the panic tbh

2023-07-06 08:17 UTC, sotnikov-s requested changes
misclick: I meant to request changes

2023-07-06 13:25 UTC, sotnikov-s approved these changes

2023-07-10 10:56 UTC, pr0n00gler approved these changes

2023-07-10 10:57 UTC, foxpy approved these changes

2023-07-11 13:03 UTC, merged