feat: set commit timeout #ntrn-79
neutron-org/neutron pull request #294
Opened 2023-07-26 11:57 UTC by NeverHappened

https://hadronlabs.atlassian.net/browse/NTRN-79

checked only by printing in server config in cmd, it's hard to discover cometbft settings in runtime

2023-07-27 11:30 UTC, pr0n00gler requested changes
Please fix linter issues

2023-07-27 11:36 UTC, NeverHappened commented
I think it's base branch issues, waiting to rebase on fix of them

2023-07-30 13:21 UTC, foxpy commented
@NeverHappened you have merge conflicts by the way

2023-08-03 13:49 UTC, pr0n00gler requested changes

2023-08-03 13:49 UTC, pr0n00gler commented on cmd/neutrond/root.go
> +			err = server.InterceptConfigsPreRunHandler(cmd, customTemplate, customNeutronConfig, tmcfg.DefaultConfig())
You can just create our own `DefaultConfig()` instead of `tmcfg.DefaultConfig()` with `timeout_commit = 5s`

2023-08-04 17:29 UTC, NeverHappened commented
https://github.com/neutron-org/neutron-tests/actions/runs/5764927281

2023-08-07 10:16 UTC, pr0n00gler approved these changes

2023-08-07 10:17 UTC, swelf19 approved these changes

2023-08-08 13:02 UTC, merged