feat: contract manager resubmit #ntrn-84
neutron-org/neutron pull request #301
Opened 2023-08-09 13:50 UTC by NeverHappened

https://hadronlabs.atlassian.net/browse/NTRN-84

2023-08-17 21:41 UTC, NeverHappened commented
https://github.com/neutron-org/neutron-tests/actions/runs/5896212533

2023-08-17 21:44 UTC, NeverHappened commented
https://github.com/neutron-org/neutron-tests/actions/runs/5896234877

2023-08-18 13:51 UTC, pr0n00gler requested changes

2023-08-18 13:51 UTC, pr0n00gler commented on x/contractmanager/keeper/failure.go
> +	case "ack":
Let's make it a constant

2023-08-18 13:51 UTC, pr0n00gler commented on x/contractmanager/keeper/failure.go
> +	case "timeout":
Let's make it a constant

2023-08-18 13:51 UTC, pr0n00gler commented on x/contractmanager/keeper/failure.go
> +			if err != nil {
Combine it into one line please

```
if _, err := k.SudoResponse(ctx, contractAddr, *failure.Packet, failure.Ack.GetResult()); err != nil {
```

2023-08-18 13:51 UTC, pr0n00gler commented on x/contractmanager/keeper/failure.go
> +			if err != nil {
Combine it into one line please

```
if _, err := k.SudoError(ctx, contractAddr, *failure.Packet, failure.Ack.GetError()); err != nil {
```

2023-08-18 13:51 UTC, pr0n00gler commented on x/contractmanager/keeper/failure.go
> +		if err != nil {
Combine it into one line please

```
if _, err := k.SudoTimeout(ctx, contractAddr, *failure.Packet); err != nil {
```

2023-08-18 13:51 UTC, pr0n00gler commented on x/transfer/ibc_handlers.go
> +		im.ContractManagerKeeper.AddContractFailure(ctx, &packet, senderAddress.String(), "ack", &ack)
Use the constant for "ack" i told above please

2023-08-18 13:51 UTC, pr0n00gler commented on x/transfer/ibc_handlers.go
> +	defer im.outOfGasRecovery(ctx, newGasMeter, senderAddress, packet, data, "timeout", nil)
Use the constant for "timeout" i told above please

2023-08-21 17:35 UTC, NeverHappened commented
TODO_RELAYER_NODE

2023-08-21 17:35 UTC, NeverHappened commented
https://github.com/neutron-org/neutron-tests/actions/runs/5929600149

2023-08-22 08:52 UTC, NeverHappened commented
https://github.com/neutron-org/neutron-tests/actions/runs/5936584543

2023-08-22 12:53 UTC, NeverHappened commented
https://github.com/neutron-org/neutron-tests/actions/runs/5939048525

2023-08-22 15:04 UTC, pr0n00gler approved these changes

2023-08-22 15:10 UTC, NeverHappened commented
https://github.com/neutron-org/neutron-tests/actions/runs/5939743946

2023-08-25 13:22 UTC, swelf19 commented on wasmbinding/bindings/query.go
> +type FailuresResponse struct {
lets move request and response next each other

2023-08-25 13:22 UTC, swelf19 commented on wasmbinding/message_plugin.go
> +	data, err := json.Marshal(&resp)
we marshal a lot of empty responses here. Do we realy need process every error? or we can save a couple of lines with 100% working json.MustMarshal? Or even return `[]byte("{}")`

2023-08-25 13:22 UTC, swelf19 commented on wasmbinding/message_plugin.go
> +	if failure.Address != contractAddr.String() {
looks like unnecessary check, we `GetFailure` for a certain address. How is it possible we get something else.

2023-08-25 13:22 UTC, swelf19 commented on x/contractmanager/keeper/failure.go
> +	if failure.Packet == nil {
During the migration we set `failure.Packet = nil` for old failures, is there a way to process those failures and remove them from the storage

2023-08-25 13:22 UTC, swelf19 commented on wasmbinding/test/custom_message_test.go
> +	suite.messenger.ContractmanagerKeeper.AddContractFailure(suite.ctx, &packet, testutil.TestOwnerAddress, "timeout", &ack)
Actually there is no `ack` on timeout, and pls replace "timeout" with the const

2023-08-25 14:03 UTC, pr0n00gler commented on wasmbinding/message_plugin.go
> +	data, err := json.Marshal(&resp)
Why is it empty by the way? Should we put failure id in the response?

2023-08-25 14:23 UTC, swelf19 commented on wasmbinding/message_plugin.go
> +	data, err := json.Marshal(&resp)
i think its not necessary, a user sends failureID to resubmit

2023-08-25 14:28 UTC, pr0n00gler commented on wasmbinding/message_plugin.go
> +	data, err := json.Marshal(&resp)
But he may want to do something after the resubmit based on that id. I actually think we should always return of an entity in our bindings

2023-08-28 10:40 UTC, NeverHappened commented
https://github.com/neutron-org/neutron-tests/actions/runs/5998807948

2023-08-29 08:10 UTC, swelf19 approved these changes

2023-08-29 08:35 UTC, pr0n00gler approved these changes

2023-08-29 13:10 UTC, quasisamurai approved these changes

2023-08-29 13:14 UTC, merged