feat: add axlr reward denom
neutron-org/neutron pull request #305
Opened 2023-08-18 13:57 UTC by NeverHappened

https://hadronlabs.atlassian.net/browse/NTRN-87

2023-08-23 08:52 UTC, pr0n00gler requested changes
There are conflicts in your PR, please resolve them

2023-08-23 08:52 UTC, pr0n00gler commented on app/upgrades/nextupgrade/upgrades.go
> +	// add new denom
Please specify what denom is that exactly

2023-08-23 09:00 UTC, pr0n00gler requested changes

2023-08-23 09:00 UTC, pr0n00gler commented on app/upgrades/nextupgrade/upgrades_test.go
> +	var denomsBefore []string
There should be "ntrtn" actually, cause we have it on mainnet currently

2023-08-23 11:04 UTC, pr0n00gler approved these changes

2023-08-25 11:32 UTC, swelf19 approved these changes

2023-08-28 09:48 UTC, merged