feat(app): Integrate the block-sdk
neutron-org/neutron pull request #413
Opened 2024-01-19 21:15 UTC by nivasan1

## 🤜  🤛 From Skip!
### In This PR 
- I integrate the block-sdk
    - I integrate the mev, default lanes (ordered accordingly) into the `LaneMempool` which will be used as the app's `Mempool`
    - I integrate the Prepare / ProcessProposal handlers and custom CheckTx handlers
         - Prepare / ProcessProposal will be responsible for building blocks
         - The CheckTx handler is responsible for
             - Performing extra verification on bid-txs
             - Purging txs from cometBFT's mempool if they aren't in the app
    - Modules
        - I integrate the `x/auction` module, and the corresponding `AnteHandler` for the auction module
### Testing
- We've tested this integration against our own set of load-tests. These tests, spin up a network of 5 nodes (3 val, 1 seed, 1 full). Perform various perturbations against them (killing, restarting, disconnecting from the network, etc.), and periodically send a load of 350 tx/sec for 90s. The output from one of our trials is [here](https://snapshots.raintank.io/dashboard/snapshot/y23ErIIGdQEL8AXCbFdv4grb2hxldbMz?orgId=2), happy to go through these in more depth / review the methodology.
### Let's Discuss
- I configured the x/auction module in the `v202` upgrade handler. The params chosen are [here](https://github.com/skip-mev/neutron/pull/2/files#diff-7c95504b0c554fdd10576f31ea32ca63a0321c2ddf0bb85f79821c3257b0b338R22), happy to change these if requested
- I also configured the lane mempool capacities / other parameters [here](https://github.com/skip-mev/neutron/pull/2/files#diff-802c8455e6cfe3da0a5fb5d9ff1f32ca2e651f0a0434163eb700887a0c871391R11)

2024-01-19 21:19 UTC, pr0n00gler commented
Thx!

2024-01-23 16:32 UTC, pr0n00gler requested changes
Could you move the

2024-01-23 16:32 UTC, pr0n00gler commented on app/upgrades/v2.0.2/constants.go
> +	AuctionParamsReserveFee      = sdk.Coin{Denom: "untrn", Amount: sdk.NewInt(1_000_000)}
Please make it 500_000 (0.5NTRN)

2024-01-23 16:32 UTC, mmikev commented on app/upgrades/v2.0.2/constants.go
> +	AuctionParamsMinBidIncrement = sdk.Coin{Denom: "untrn", Amount: sdk.NewInt(1_000_000)}
Please make it 100_000 (0.1NTRN)

2024-01-23 16:32 UTC, mmikev commented on app/upgrades/v2.0.2/upgrades.go
> +func setAuctionParams(ctx sdk.Context, feeBurnerKeeper *feeburnerkeeper.Keeper, auctionKeeper auctionkeeper.Keeper) error {
Could you create a `nextupgrade` folder in the `upgrades` folder and put this params set in the newly created upgrade handler, pls?

Like here: https://github.com/neutron-org/neutron/pull/414/files#diff-16b23f75ba28a93ca5912d821b29a53db322c7736f895454870c6e318efdecfe

2024-01-23 16:43 UTC, pr0n00gler commented on app/upgrades/v2.0.2/upgrades.go
> +func setAuctionParams(ctx sdk.Context, feeBurnerKeeper *feeburnerkeeper.Keeper, auctionKeeper auctionkeeper.Keeper) error {
Basically move all block-sdk related stuff into the `nextupgrade` folder instead of `2.0.2`

2024-01-23 22:37 UTC, pr0n00gler requested changes
[Tests](https://github.com/neutron-org/neutron/actions/runs/7631527306/job/20789666853?pr=413) do no pass unfortunately :(
You can run it via `make test`

Please fix it:

```
--- FAIL: TestKeeperTestSuite (0.19s)
    --- FAIL: TestKeeperTestSuite/TestAuctionUpgrade (0.19s)
        suite.go:87: test panicked: ApplyUpgrade should never be called without first checking HasHandler
            goroutine 24 [running]:
            runtime/debug.Stack()
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
            github.com/stretchr/testify/suite.failOnPanic(0x14000f084e0, {0x103212ba0, 0x1036a76f0})
...
```

2024-01-26 14:17 UTC, swelf19 commented on app/app.go
> +	app.SetEndBlocker(app.EndBlocker)
the same method called on L1016, pls remove one of

2024-01-26 14:17 UTC, swelf19 commented on app/app.go
>  	app.SetEndBlocker(app.EndBlocker)
```suggestion
```

2024-01-26 14:17 UTC, swelf19 commented on app/app.go
> +	MEVLane auctionante.MEVLane
Not sure we need to define a field for `auctionante.MEVLane`, the only place you use it is L1000, passing it to antehandler, but you can do it without an app's field

2024-01-30 20:00 UTC, nivasan1 commented on go.mod
> +go 1.21.4
patch version updated so that test / lint would run successfully

2024-01-30 20:17 UTC, g3ndo9kar9 commented on app/app.go
> +	app.SetProcessProposal(baseapp.NoOpProcessProposal())
Setting ProcessProposal to a nop

2024-01-31 14:05 UTC, pr0n00gler approved these changes

2024-01-31 14:05 UTC, merged