add env from stateful relayer
neutron-org/neutron pull request #42
Opened 2022-08-26 08:33 UTC by quasisamurai

Needs to be merged w [this task](https://github.com/neutron-org/cosmos-query-relayer/pull/22)

2022-08-26 10:28 UTC, sotnikov-s approved these changes
tested manually and using tx query test of mine: works perfectly

2022-08-26 12:48 UTC, swelf19 approved these changes, later dismissed

2022-08-26 13:06 UTC, sotnikov-s requested changes

2022-08-26 13:06 UTC, sotnikov-s commented on docker-compose.yml
> +      - RELAYER_STORAGE_PATH=storage/leveldb
let's stick to the pattern of folders that entities are use, e.g. home dir for neutron chain is `/data/test-1`, so let's make the relayer's storage folder be similar to it, for instance `/data/relayer/storage/leveldb`

2022-08-26 15:42 UTC, foxpy approved these changes

2022-08-26 16:01 UTC, sotnikov-s approved these changes

2022-08-26 16:01 UTC, swelf19 approved these changes

2022-08-29 08:29 UTC, pr0n00gler approved these changes

2022-08-29 08:36 UTC, ratik approved these changes

2022-08-29 10:15 UTC, merged