chore(x): bit of proofreading
neutron-org/neutron pull request #426
Opened 2024-01-27 23:15 UTC by Ursulafe

Came across few errors, one is a plain text file, rest are comments

2024-01-30 12:01 UTC, swelf19 approved these changes

2024-01-31 11:44 UTC, quasisamurai approved these changes

2024-02-02 12:51 UTC, quasisamurai requested changes
Actually, i've noticed that you edited proto-generated files manually. We're not allowing this for obvious reasons. Please, make sure to run  `make proto-gen`

2024-04-23 10:47 UTC, pr0n00gler commented
https://github.com/neutron-org/neutron/pull/496

2024-04-23 10:47 UTC, closed without merging