feat: multihop return dust
neutron-org/neutron pull request #438
Opened 2024-02-15 11:01 UTC by NeverHappened

2024-02-15 12:19 UTC, NeverHappened commented on x/dex/keeper/integration_multihopswap_test.go
> +func (s *DexTestSuite) TestBugWithLiquidityCheck() {
Hey @NicholasDotSol @jcompagni10 

This test demonstrates behavior that I'm not sure is correct.
So we setup pools, such that:
- A is much cheaper than B
- B is much more expensive than C

In this scenario with multihop swap, on a step with B to C exchange we have:
1,002TokenB and try to exchange it to TokenC.
Inside the `Pool.Swap()` it will calculate that we swap 1,001TokenB to 22,015,000C. As you see that's one token less that we wanted to swap.
This have consequnces:
- We have different real price of TokenB to TokenC that we could have (and should?)
- We leave 1TokenB, and in multihop swap scenario it will try to swap it using next pool (because the condition for orderFilled=true is not satisfied). In this test however there is no more pools left, so it just fails the multihop with error "Insufficient liquidity" that is definitely incorrect - pool had enough liquidity.
So question is: what do you think - is it correct behavior? What can we do with multihop scenario?

2024-02-27 14:13 UTC, pr0n00gler requested changes

2024-02-27 14:13 UTC, mmikev commented on x/dex/keeper/multihop_swap.go
> +	dust = sdk.Coin.Sub(sdk.NewCoin(swapAmountTakerDenom.Denom, amountIn), swapAmountTakerDenom)
Why do we need to do a substraction here?
Isn't `swapAmountTakerDenom` already a dust amount?

2024-02-27 14:13 UTC, mmikev commented on x/dex/keeper/integration_multihopswap_test.go
> +func (s *DexTestSuite) TestMultiHopSwapSingleRouteWithDust() {
Let's add a testcase where Alice receives not only TokenA dust, but also dust of other tokens

2024-02-27 14:22 UTC, NeverHappened commented on x/dex/keeper/multihop_swap.go
> +	dust = sdk.Coin.Sub(sdk.NewCoin(swapAmountTakerDenom.Denom, amountIn), swapAmountTakerDenom)
I think no, [here](https://github.com/neutron-org/neutron/blob/0085ad29a76a11fd5d124b774e1b06b64e716cc0/x/dex/keeper/liquidity.go#L89) you can see it returns INPUT - DUST

2024-02-27 14:23 UTC, NeverHappened commented on x/dex/keeper/integration_multihopswap_test.go
> +func (s *DexTestSuite) TestMultiHopSwapSingleRouteWithDust() {
There is such a testcase just below (TestMultiHopSwapSingleRouteWithManyDustTokens)

2024-02-27 14:24 UTC, pr0n00gler commented on x/dex/keeper/multihop_swap.go
> +	dust = sdk.Coin.Sub(sdk.NewCoin(swapAmountTakerDenom.Denom, amountIn), swapAmountTakerDenom)
Ah, so basically it's the amount that was swapped

2024-02-27 14:28 UTC, mmikev commented on x/dex/keeper/multihop_swap.go
> +	dust = sdk.Coin.Sub(sdk.NewCoin(swapAmountTakerDenom.Denom, amountIn), swapAmountTakerDenom)
Not quite good naming and comment coverage honestly

2024-02-27 14:29 UTC, pr0n00gler commented on x/dex/keeper/integration_multihopswap_test.go
> +func (s *DexTestSuite) TestMultiHopSwapSingleRouteWithDust() {
Ah, didn't see that

2024-02-29 16:18 UTC, jcompagni10 approved these changes, later dismissed
Lgtm

2024-02-29 16:18 UTC, jcompagni10 commented on x/dex/keeper/integration_multihopswap_test.go
> +func (s *DexTestSuite) TestBugWithLiquidityCheck() {
Will look more closely in a bit. But At first glance if we try to swap 60_000_000TokenA we should get out 1002 tokenB but the pool is only funded with 1TokenB

2024-03-01 11:46 UTC, swelf19 submitted a review, later dismissed

2024-03-01 11:46 UTC, swelf19 commented on x/dex/keeper/multihop_swap.go
> +	var currentDust sdk.Coin
A small suggestion, rename all `current` to `step`, i think the `step` name  fits better for variables usage.

2024-03-01 12:30 UTC, pr0n00gler submitted a review, later dismissed

2024-03-01 12:47 UTC, swelf19 approved these changes, later dismissed

2024-03-01 15:15 UTC, sotnikov-s commented on x/dex/keeper/core.go
> +	}
we can optimise the transfer by sending both coinOut and dust in a single operation:
```go
err = k.bankKeeper.SendCoinsFromModuleToAccount(
	ctx,
	types.ModuleName,
	receiverAddr,
	append(bestRoute.dust, bestRoute.coinOut), <<<<<<<<<<<<<
)
```

2024-03-01 15:15 UTC, sotnikov-s commented on x/dex/keeper/integration_multihopswap_test.go
> +	s.assertAccountBalanceWithDenomInt(s.alice, "TokenD", math.NewInt(24)) // received TokenD after swap
I wonder if it's good in terms of UX — to have TokenB received when making a TokenA -> TokenD swap. have you guys considered making backwards swaps for intermediate token dust? e.g. in this example we could swap all the TokenB dust back to TokenA and as a result have only TokenA and TokenD on the user's wallet

2024-03-01 15:15 UTC, sotnikov-s commented on x/dex/keeper/integration_multihopswap_test.go
> +	s.assertAccountBalanceWithDenomInt(s.alice, "TokenA", math.NewInt(2))
```suggestion
	s.assertAccountBalanceWithDenomInt(s.alice, "TokenA", math.NewInt(2)) // dust left
```

2024-03-04 08:40 UTC, NeverHappened commented on x/dex/keeper/integration_multihopswap_test.go
> +	s.assertAccountBalanceWithDenomInt(s.alice, "TokenD", math.NewInt(24)) // received TokenD after swap
Interesting suggestion, not sure if needed.
Cons is that there is no guarantee we can swap back until the TokenA. 
Also can be a little taxing on the efficiency?

2024-03-04 08:51 UTC, NeverHappened commented on x/dex/keeper/integration_multihopswap_test.go
> +func (s *DexTestSuite) TestBugWithLiquidityCheck() {
Oh this was just mistake in commenting. Indeed if you swap 60000000 you should get 1002 tokenB.

2024-03-05 10:08 UTC, sotnikov-s approved these changes, later dismissed

2024-03-07 10:19 UTC, swelf19 approved these changes, later dismissed

2024-03-07 20:31 UTC, pr0n00gler submitted a review, later dismissed

2024-03-21 16:06 UTC, merged