Add missing pagination to dex CLI queries
neutron-org/neutron pull request #462
Opened 2024-03-12 05:29 UTC by jcompagni10

2024-03-12 05:32 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/8244074023

2024-03-15 12:17 UTC, NeverHappened submitted a review, later dismissed

2024-03-19 12:45 UTC, pr0n00gler approved these changes

2024-03-21 16:05 UTC, quasisamurai approved these changes, later dismissed

2024-03-21 20:59 UTC, pr0n00gler requested changes

2024-03-21 20:59 UTC, pr0n00gler commented on x/dex/client/cli/query_pool_reserves.go
>  			pageReq, err := client.ReadPageRequest(cmd.Flags())
I'm not sure `list-pool-reserves` has pagination flags
<img width="949" alt="Screenshot 2024-03-21 at 10 58 31 PM" src="https://github.com/neutron-org/neutron/assets/6247919/d9c45300-5301-4a51-ac22-179d66fe5fae">

2024-03-28 20:13 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/8473138806

2024-03-28 20:38 UTC, pr0n00gler approved these changes

2024-04-01 10:13 UTC, merged