chore: bumped wasmd version to v0.28.0
neutron-org/neutron pull request #47
Opened 2022-09-06 07:28 UTC by swelf19

implements https://p2pvalidator.atlassian.net/jira/software/projects/LSC/boards/121?selectedIssue=LSC-146

wasmd fork was updated to v0.28.0 and event filtering was disabled https://github.com/neutron-org/wasmd/commit/600e1f7c39a230c513301be1f4ee4a4cec87392c

2022-09-07 06:57 UTC, foxpy requested changes
This breaks `test:simple` in our integration tests framework

2022-09-07 09:15 UTC, swelf19 commented
> This breaks `test:simple` in our integration tests framework

breaking changes in the commit  https://github.com/CosmWasm/wasmd/commit/ee44cc06d0a6c8a35c5657cb765f6c6ba39902fa that part of 0.28.0 release

2022-09-07 10:14 UTC, foxpy commented
> breaking changes in the commit [CosmWasm/wasmd@ee44cc0](https://github.com/CosmWasm/wasmd/commit/ee44cc06d0a6c8a35c5657cb765f6c6ba39902fa) that part of 0.28.0 release

Are we going to revert this commit (sounds dangerous) or try to build stuff differently without relying on events somehow?

2022-09-07 10:17 UTC, pr0n00gler commented
> > breaking changes in the commit [CosmWasm/wasmd@ee44cc0](https://github.com/CosmWasm/wasmd/commit/ee44cc06d0a6c8a35c5657cb765f6c6ba39902fa) that part of 0.28.0 release
> 
> Are we going to revert this commit (sounds dangerous) or try to build stuff differently without relying on events somehow?

We can't just revert it because it's very important security commit. We're trying to deal with the problems without relying on events.

2022-09-12 10:15 UTC, foxpy requested changes

2022-09-12 10:15 UTC, foxpy commented on wasmbinding/bindings/msg.go
> +	// Channek is a src channel on neutron side trasaction was submitted from
```suggestion
	// Channel is a src channel on neutron side transaction was submitted from
```

2022-09-12 10:55 UTC, foxpy submitted a review, later dismissed

2022-09-13 15:34 UTC, foxpy approved these changes

2022-09-14 07:33 UTC, oopcode commented on proto/interchaintxs/v1/tx.proto
> +  string channel = 2;
channel_id?

2022-09-14 08:04 UTC, oopcode approved these changes

2022-09-14 09:13 UTC, merged