sdk 50 NTRN-230
neutron-org/neutron pull request #483
Opened 2024-04-11 00:50 UTC by quasisamurai

2024-04-15 07:26 UTC, pr0n00gler commented
Please change the target branch to feat/sdk-50 and fix linter issues

2024-04-15 07:30 UTC, pr0n00gler requested changes

2024-04-15 07:30 UTC, mmikev commented on x/tokenfactory/keeper/msg_server.go
> +		return nil, types.ErrDenomDoesNotExist.Wrapf("need: %s, received: %s, denom: %s", authorityMetadata.GetAdmin(), msg.Sender, msg.Denom)
Huh?
The error doesn't seem right

2024-04-15 07:30 UTC, mmikev commented on x/tokenfactory/types/msgs.go
> -
Why it is removed?

2024-04-15 07:30 UTC, mmikev commented on x/tokenfactory/types/msgs.go
What's the point of the changes here?

2024-04-24 12:36 UTC, pr0n00gler approved these changes

2024-04-24 12:36 UTC, merged