Allow dex operation to be paused
neutron-org/neutron pull request #487
Opened 2024-04-17 10:33 UTC by jcompagni10

Allow dex to be paused in the event of hack or other issues to ensure the rest of neutron chain can continue to run normally

2024-05-10 01:39 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/9025944477

2024-05-10 01:48 UTC, NicholasDotSol approved these changes

2024-05-13 12:34 UTC, pr0n00gler requested changes
Please add a state migration which updates the DEX storage and particularly params state with added `paused` field

2024-05-14 20:01 UTC, jcompagni10 commented
> Please add a state migration which updates the DEX storage and particularly params state with added `paused` field

done

2024-05-14 20:01 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/9084416344

2024-05-20 09:57 UTC, swelf19 reviewed
LGTM. But i do not see any tests at all. Could you add some.
1) You can pause
2) You can unpause
3) you can not perform any operation while dex is paused

Rerun integration tests pls, test run is failed.

2024-05-20 11:38 UTC, swelf19 reviewed
It's kinda strange we bump version for old params, doesn't it? Why cant we just a third param to the current params and do not create old v2

2024-05-21 17:56 UTC, joldie777 requested changes

2024-05-21 17:56 UTC, joldie777 commented on x/dex/keeper/migrations.go
> +// Migrate1to2 migrates from version 1 to 2.
Migrate2to3

2024-05-23 18:29 UTC, jcompagni10 commented
> It's kinda strange we bump version for old params, doesn't it? Why cant we just a third param to the current params and do not create old v2

Perhaps I'm mistaken, but it seemed like bad practice to try and marshall the old params from the kvstore using the new proto definition. https://github.com/neutron-org/neutron/blob/feat%2Fpause_dex/x/dex/migrations/v3/store.go#L30

I played around and it does seem to work, but I still didn't feel comfortable taking the risk. @swelf19

2024-05-24 02:38 UTC, jcompagni10 commented
> LGTM. But i do not see any tests at all. Could you add some.
> 
> 1. You can pause
> 2. You can unpause
> 3. you can not perform any operation while dex is paused
> 
> Rerun integration tests pls, test run is failed.

done

2024-05-24 02:43 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/9217868646

2024-05-24 09:07 UTC, swelf19 approved these changes

2024-05-24 09:12 UTC, joldie777 approved these changes

2024-05-24 09:14 UTC, merged