Cancel LOs at BeginBlock & max JITs
neutron-org/neutron pull request #504
Opened 2024-04-30 05:45 UTC by jcompagni10

Move expiring limit order purge to BeginBlock.
Enforce a maximum number of JITs per block. 

This allows JITs to be visible to dex aggregators and other integrators. 

Also, enforce a maximum number of JITs per block: this eliminates a DOS threat and creates more efficient market for JIT space.

2024-05-01 09:35 UTC, pr0n00gler approved these changes, later dismissed

2024-05-10 01:32 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/9025914455

2024-05-13 15:08 UTC, swelf19 reviewed
With applying this  it is safe to remove ` EnsureBlockGasMeter` method in the app.go file, right?

2024-05-13 15:08 UTC, swelf19 commented on x/dex/types/params.pb.go
> +	Max_JITsPerBlock      uint64                                               `protobuf:"varint,3,opt,name=max_JITs_per_block,json=maxJITsPerBlock,proto3" json:"max_JITs_per_block,omitempty"`
Usually we serialize json field name with snake_case, let's do it the same way.

2024-05-13 15:43 UTC, jcompagni10 commented
> With applying this it is safe to remove  EnsureBlockGasMeter method in the app.go file, right?

No, we still need it for limitOrder tranche key generation.

2024-05-13 15:51 UTC, jcompagni10 commented on x/dex/types/params.pb.go
> +	Max_JITsPerBlock      uint64                                               `protobuf:"varint,3,opt,name=max_JITs_per_block,json=maxJITsPerBlock,proto3" json:"max_JITs_per_block,omitempty"`
What is not snaked cased? Is the issue the capitalization of JIT?

2024-05-13 15:51 UTC, jcompagni10 commented on x/dex/types/params.pb.go
> +	Max_JITsPerBlock      uint64                                               `protobuf:"varint,3,opt,name=max_JITs_per_block,json=maxJITsPerBlock,proto3" json:"max_JITs_per_block,omitempty"`
@swelf19

2024-05-13 15:59 UTC, swelf19 commented
> > With applying this it is safe to remove  EnsureBlockGasMeter method in the app.go file, right?
> 
> No, we still need it for limitOrder tranche key generation. @swelf19

i mean we don't need to require MaxGas to be set anymore, no? I don't see where we use it

2024-05-13 16:04 UTC, jcompagni10 commented
> i mean we don't need to require MaxGas to be set anymore, no? I don't see where we use it
Ah yes, you are correct.

2024-05-14 16:57 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/9083217334

2024-05-24 23:26 UTC, NicholasDotSol approved these changes

2024-05-27 12:11 UTC, pr0n00gler commented
> https://github.com/neutron-org/neutron-tests/actions/runs/9083217334

This is definitely a wrong branch of Neutron in the test-run, please attach a correct one

<img width="365" alt="Screenshot 2024-05-27 at 3 10 47 PM" src="https://github.com/neutron-org/neutron/assets/6247919/3717c884-772f-4199-b613-ece4da15276e">

2024-05-27 12:11 UTC, pr0n00gler requested changes
> https://github.com/neutron-org/neutron-tests/actions/runs/9083217334

This is definitely a wrong branch of Neutron in the test-run, please attach a correct one

<img width="365" alt="Screenshot 2024-05-27 at 3 10 47 PM" src="https://github.com/neutron-org/neutron/assets/6247919/3717c884-772f-4199-b613-ece4da15276e">

2024-05-27 16:46 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/9258053489

2024-05-27 17:26 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/9258429370

2024-05-28 09:04 UTC, pr0n00gler approved these changes

2024-05-28 14:38 UTC, swelf19 approved these changes

2024-05-28 15:04 UTC, merged