fix: update slinky version
neutron-org/neutron pull request #516
Opened 2024-05-08 21:04 UTC by aljo242

Update slinky to the latest version
- includes latest version of `x/marketmap` (previous version was outdated)
- make some `go.mod` changes to keep compatible with neutron sdk fork
- update upgrade handler for params

@pr0n00gler i will be following this up with an upgrade handler to initialize the `x/oracle` and `x/marketmap` states!

2024-05-13 12:31 UTC, pr0n00gler approved these changes

2024-05-13 14:33 UTC, swelf19 approved these changes

2024-05-13 18:21 UTC, pr0n00gler requested changes
Please upgrade init-neutrond.sh (particularly [this](https://github.com/neutron-org/neutron/blob/02a1b891fc152a65b24bccc6eb6c21a77b38a75c/network/init-neutrond.sh#L739) line) accordingly

2024-05-14 09:02 UTC, pr0n00gler approved these changes

2024-05-14 09:03 UTC, merged