Feat/Behind Enemy Lines enforcement
neutron-org/neutron pull request #527
Opened 2024-05-14 21:02 UTC by jcompagni10

Prevent users from depositing behind enemy lines. 

This is critical for prevent a DOS vector where users deposit many ticks of dust causing swaps to have to touch a large number of ticks. By preventing users from depositing at a price cheaper than the opposing token price (ie. on the wrong side of the spread), we greatly limit the surface area for ticks that can be dusted. Most ticks near the spread will already have liquidity so dusting is impossible or limit to a small set of un-used fee tiers. While users can still place dust towards the back of the order book this will not effect swaps. 

Additionally, this maintains a nice invariant that all liquidity in the dex exists across a partitioned spread with no overlap in prices.

2024-05-14 21:08 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/9086152025

2024-05-24 12:46 UTC, joldie777 approved these changes

2024-05-24 23:29 UTC, NicholasDotSol approved these changes

2024-05-27 10:38 UTC, NeverHappened requested changes

2024-05-27 10:38 UTC, NeverHappened commented on x/dex/keeper/core.go
> +			if options.FailTxOn_BEL {
why not FailTxOnBEL? kinda breaks the naming

2024-05-27 10:38 UTC, NeverHappened commented on x/dex/keeper/core.go
> +		options := options[i]
maybe better `option := options[i]`
to avoid rewriting base var

2024-05-27 10:38 UTC, NeverHappened commented on proto/neutron/dex/tx.proto
> +  bool fail_tx_on_BEL = 2;
why not fail_tx_on_bel?

2024-05-28 09:13 UTC, pr0n00gler approved these changes

2024-05-28 13:17 UTC, quasisamurai approved these changes

2024-05-31 00:02 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/9276692068

2024-05-31 11:21 UTC, pr0n00gler commented
Resolve conflicts, pls

2024-05-31 13:41 UTC, pr0n00gler approved these changes

2024-05-31 13:47 UTC, merged