Chore: Flip Dex Price Logic #NTRN-355
neutron-org/neutron pull request #624
Opened 2024-07-11 19:12 UTC by jcompagni10

**Issue**
https://hadronlabs.atlassian.net/browse/NTRN-355?atlOrigin=eyJpIjoiYTI0ODY0YTRhNzdhNDQ1NWFlODZhNzE0N2E0ZDk2MmYiLCJwIjoiaiJ9

Currently the dex stores prices as 1.0001^-TickIndex
This has been a persistent confusion for builders and integrators and also introduces unnecessary loss of precision. We can safely flip prices the other way without changing functionality

2024-07-31 23:59 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/10189392992

2024-08-05 18:44 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/10254298350

2024-08-05 21:40 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/10256440025

2024-08-14 11:39 UTC, pr0n00gler requested changes

2024-08-14 11:39 UTC, pr0n00gler commented on x/dex/migrations/v4/store.go
Hm, could you clarify why do you change a code for the previous migration?

I don't think we are supposed to change old migrations

2024-08-20 00:38 UTC, jcompagni10 commented on x/dex/migrations/v4/store.go
`MustCalcPrice` fn has been inverted so to achieve the same migration we must flip the sign. The output of the migration should be the same

2024-08-20 00:40 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/10256440025

2024-08-28 14:22 UTC, pr0n00gler commented
Unit tests don't work, please fix it

2024-09-02 11:04 UTC, swelf19 commented on x/dex/keeper/limit_order_tranche.go
> +		MakerPrice:         price,
Does it mean `PriceTakerToMaker` is unused now? Lets it remove it then.

2024-09-02 11:04 UTC, swelf19 commented on proto/neutron/dex/pool_reserves.proto
> +    (gogoproto.jsontag) = "maker_price"
it's a matter of taste, but i like name `price_maker_to_taker` better as an opposite price

2024-09-02 11:04 UTC, swelf19 commented on x/dex/migrations/v4/store.go
I think the question was - do we get the same migration output in 2 cases
1) Our case. User migrates 3 -> 4 (old one) (neutron v4.2.1) and then 4 -> 5. **3 -> old 4 -> 5**
2) Imported dex module to third parthy project. User migrates 3 vesrion -> 5 version (current one).  **3 -> new 4 -> 5**

I dont think it's safe in terms compatibility to modify already released migrations

2024-09-02 11:06 UTC, pr0n00gler commented on x/dex/migrations/v4/store.go
Yes, that's exactly what i meant

2024-09-03 18:41 UTC, jcompagni10 commented on proto/neutron/dex/pool_reserves.proto
> +    (gogoproto.jsontag) = "maker_price"
Just to clarify. The plan is to remove the field `price_taker_to_maker` in the following release. I agree that if we were keeping both they should be named similarly. Personally, I have always, found `price_taker_to_maker` confusing. It is ambiguous whether it is referring to the price the maker will pay for the taker denom or the rate at which maker denoms can be exchanged for taker denoms. IMHO `maker_price` is a clearer description of the price at which the maker is selling a token. 
That being said, a primary goal of this PR is to eliminate confusion around naming conventions, so if the consensus is that `price_maker_to_taker` is clearer I am happy to go with that. 

@swelf19 @pr0n00gler @NicholasDotSol  Thoughts here?

2024-09-03 18:42 UTC, jcompagni10 commented on x/dex/keeper/limit_order_tranche.go
> +		MakerPrice:         price,
The plan is to remove it. But for compatibility, I think its better to deprecate first and then remove in the subsequent release.

2024-09-03 18:49 UTC, jcompagni10 commented on x/dex/migrations/v4/store.go
I don't think it's an issue. You can see that the tests are unchanged. So the migrations still produce the same output. @swelf19 @pr0n00gler

2024-09-03 19:42 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/10689531672

2024-09-19 22:19 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/10949752474

2024-09-19 22:20 UTC, jcompagni10 commented
I'm assuming this: 
> I think the question was - do we get the same migration output in 2 cases

Our case. User migrates 3 -> 4 (old one) (neutron v4.2.1) and then 4 -> 5. 3 -> old 4 -> 5
Imported dex module to third parthy project. User migrates 3 vesrion -> 5 version (current one). 3 -> new 4 -> 5

Was resolved by the comment above @swelf19, please correct me if not

2024-09-24 20:39 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/11021574416

2024-09-25 01:45 UTC, NicholasDotSol commented on proto/neutron/dex/pool_reserves.proto
> +    (gogoproto.jsontag) = "maker_price"
agree, it only sounds more descriptive on surface level, in fact it's ambiguous

2024-09-26 09:09 UTC, NicholasDotSol commented on x/dex/keeper/liquidity.go
>  		// but due to rounding and inaccuracy of fixed decimal math, it is possible
Should update the comment on ln55

2024-10-08 14:37 UTC, swelf19 approved these changes, later dismissed
Pls resolve conflicts

2024-10-08 14:37 UTC, swelf19 commented on x/dex/types/price.go
> +	if price.LT(math_utils.OnePrecDec()) {
As far as i understand you need to update comment at line 100 -> `>=1`

2024-10-08 14:37 UTC, swelf19 commented on x/dex/migrations/v4/store.go
Yes, seems you are right. No changes in output. Dont see any problems with a migration now.

2024-10-15 03:04 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/11021574416

2024-10-15 10:40 UTC, swelf19 approved these changes

2024-10-15 13:33 UTC, merged