chore: Remove old dex migrations
neutron-org/neutron pull request #625
Opened 2024-07-11 19:16 UTC by jcompagni10

Remove old dex migrations.

There are multiple incoming PRs that conflict with these migrations. Since they are no longer necessary we can safely remove them

2024-07-15 12:11 UTC, pr0n00gler approved these changes, later dismissed

2024-07-18 20:26 UTC, joldie777 approved these changes

2024-07-22 10:09 UTC, quasisamurai approved these changes

2024-07-23 10:45 UTC, pr0n00gler requested changes
After a couple of considerations we think it's not safe to remove migrations from the module. Module is a separate entity and if i import it as a third-part developer i must get a guarantee that all changes made by developer in the code also reflected in the state by migrations. What do you think?

2024-07-23 14:33 UTC, closed without merging