intro new request & modify old one
neutron-org/neutron pull request #663
Opened 2024-08-08 09:59 UTC by quasisamurai

2024-08-13 15:36 UTC, joldie777 approved these changes, later dismissed

2024-08-14 13:06 UTC, NeverHappened requested changes

2024-08-14 13:06 UTC, NeverHappened commented on proto/neutron/contractmanager/query.proto
> +message QueryFailureRequest {
`pagination` field seems to be not needed logically (and not used) for `QueryFailureRequest`.
Please remove it

2024-08-14 13:06 UTC, NeverHappened commented on proto/neutron/contractmanager/query.proto
> +  rpc AddressFailure(QueryFailureRequest) returns (QueryFailuresResponse) {
How about making `QueryFailureResponse` struct without pagination? It seems strange that we return it in array even tho it's always one failure. And pagination always null

2024-08-14 13:08 UTC, NeverHappened commented
Also - please attach PR to neutronjs here

2024-09-02 10:52 UTC, NeverHappened approved these changes

2024-09-02 11:52 UTC, quasisamurai commented
https://github.com/neutron-org/neutron-tests/actions/runs/10584317289

2024-09-04 11:18 UTC, pr0n00gler approved these changes

2024-09-04 11:18 UTC, merged