fix: path for multiHopSwap query
neutron-org/neutron pull request #752
Opened 2024-10-17 19:23 UTC by jcompagni10

2024-10-18 17:50 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/11408496357

2024-10-20 13:44 UTC, pr0n00gler approved these changes

2024-10-21 10:58 UTC, pr0n00gler requested changes
Regenerate swagger files here, please

2024-10-21 20:44 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/11408496357

2024-10-22 10:54 UTC, pr0n00gler approved these changes

2024-10-22 10:54 UTC, merged