feat: allowed ccv,globalfee stargate queries #NTRN-408
neutron-org/neutron pull request #765
Opened 2024-11-15 14:38 UTC by swelf19

PR includes:
1) Adding new Stargate requests to the whitelist.
2) Correcting typos in existing requests.
3) Changing the Hermes configuration. This is done to align the local Hermes configuration with the version that has long been used in integration tests (https://github.com/neutron-org/neutron-integration-tests/blob/main/setup/hermes/create-conn.sh#L13). This configuration is used only when manually launching chains using the commands 'make init && make start-rly'.

Task definition: Add updateParamsPersimmon to chain manager (https://github.com/neutron-org/neutron-dao/tree/main/contracts/dao/neutron-chain-manager) for the following modules:
- consumer
- dynamicfees
- globalfee

All prs:
https://github.com/neutron-org/neutronjs/pull/10
https://github.com/neutron-org/neutronjsplus/pull/69
https://github.com/neutron-org/neutron-integration-tests/pull/368
https://github.com/neutron-org/neutron-dao/pull/116
https://github.com/neutron-org/neutron-std/pull/8
https://github.com/neutron-org/neutron/pull/765

2024-11-20 10:54 UTC, pr0n00gler commented on network/hermes/create-conn.sh
> +echo "Initiating short living client..."
Is it possible to move it into the integration tests?
Cause this seems unnecessary in Neutron itself

2024-11-20 10:55 UTC, pr0n00gler requested changes

2024-11-20 10:55 UTC, pr0n00gler commented on network/hermes/create-conn.sh
> +echo "Initiating short living client..."
Is it possible to move it into the integration tests?
Cause this seems unnecessary in Neutron itself

2024-11-21 10:12 UTC, joldie777 approved these changes, later dismissed

2024-11-25 09:17 UTC, sotnikov-s commented on network/hermes/create-conn.sh
> +echo "Initiating short living client..."
💯

2024-11-25 09:17 UTC, sotnikov-s commented on wasmbinding/stargate_allowlist.go
> +		"/feemarket.feemarket.v1.Query/GasPrices": &feemarkettypes.GasPricesResponse{},
were all these wrong before? (without leading slash)

2024-11-25 16:13 UTC, swelf19 commented on wasmbinding/stargate_allowlist.go
> +		"/feemarket.feemarket.v1.Query/GasPrices": &feemarkettypes.GasPricesResponse{},
yes

2024-11-25 16:19 UTC, swelf19 commented on network/hermes/create-conn.sh
> +echo "Initiating short living client..."
We have two sets of configurations for Hermes:
1) For use with the cosmospark in integration tests: https://github.com/neutron-org/neutron-integration-tests/blob/main/setup/hermes/create-conn.sh#L13
2) For local relay run using the commands 'make init && make start-rly'.

I standardized them, as the command has been present in the hermes (docker) configuration for quite some time.

2024-11-26 13:17 UTC, NeverHappened submitted a review, later dismissed

2024-11-27 08:43 UTC, sotnikov-s approved these changes

2024-11-27 08:49 UTC, joldie777 approved these changes

2024-11-27 11:37 UTC, pr0n00gler approved these changes

2024-11-27 11:41 UTC, merged