Feat/simplify config
neutron-org/neutron pull request #86
Opened 2022-10-27 08:43 UTC by NeverHappened

part of [this](https://p2pvalidator.atlassian.net/browse/NTRN-252)

WARN: merge after https://p2pvalidator.atlassian.net/browse/NTRN-252 !

2022-10-27 08:53 UTC, foxpy commented
> merge after https://p2pvalidator.atlassian.net/browse/NTRN-252

I guess you wanted to leave a link to PR here?

2022-11-02 15:21 UTC, oopcode approved these changes

2022-11-03 12:27 UTC, foxpy requested changes

2022-11-03 12:27 UTC, foxpy commented on docker-compose.yml
>        - RELAYER_NEUTRON_CHAIN_SIGN_MODE_STR=direct
You could as well have deleted these lines (and others like in your PR in neutron-query-relayer).

I mean, if we are cleaning up, why wouldn't we clean up everything and everywhere?

2022-11-04 00:24 UTC, foxpy approved these changes

2022-11-08 07:27 UTC, swelf19 approved these changes

2022-11-08 08:31 UTC, pr0n00gler approved these changes

2022-11-08 08:41 UTC, sotnikov-s approved these changes

2022-11-08 11:22 UTC, quasisamurai approved these changes

2022-11-08 11:24 UTC, merged