feat: NTRN-262. Add interhchain queries Init/Export Genesis
neutron-org/neutron pull request #91
Opened 2022-11-16 13:10 UTC by albertandrejev

Implement `ExportGenesis` and `InitGenesis` methods for Interchain Queries module in Neutron.

Registered Interchain Queries and other necessary info must be exported and initialised in the corresponding methods. Otherwise we won’t be able to upgrade our chain properly.

2022-11-20 12:01 UTC, pr0n00gler requested changes

2022-11-20 12:01 UTC, mmikev commented on x/interchainqueries/genesis.go
> +	// Set all registere queries
registere**d**

2022-11-20 12:01 UTC, mmikev commented on x/interchainqueries/genesis.go
> +	if genState.RegisteredQueries != nil {
Unnecessary check since you can safely iterate through nil slice

2022-11-20 12:01 UTC, mmikev commented on x/interchainqueries/genesis.go
> +			k.SaveQuery(ctx, *elem)
Unhandled error

2022-11-20 12:01 UTC, mmikev commented on x/interchainqueries/keeper/keeper.go
> +func (k Keeper) GetAllReigsteredQueries(ctx sdk.Context) []*types.RegisteredQuery {
Re**gi**stered

2022-11-21 09:22 UTC, oopcode approved these changes

2022-11-21 09:40 UTC, pr0n00gler approved these changes

2022-11-25 09:12 UTC, merged